(define (problem cyclic6)
    (:domain StrategicArgumentation)
    (:objects a i h k j m l - arg
              S0 S1 S256 S128 S1024 S512 S4096 S2048 S257 S129 S1025 S513 S4097 S2049 S384 S1280 S768 S4352 S2304 S1152 S640 S4224 S2176 S1536 S5120 S3072 S4608 S2560 S6144 S385 S1281 S769 S4353 S2305 S1153 S641 S4225 S2177 S1537 S5121 S3073 S4609 S2561 S6145 S1408 S896 S4480 S2432 S1792 S5376 S3328 S4864 S2816 S6400 S1664 S5248 S3200 S4736 S2688 S6272 S5632 S3584 S7168 S6656 S1409 S897 S4481 S2433 S1793 S5377 S3329 S4865 S2817 S6401 S1665 S5249 S3201 S4737 S2689 S6273 S5633 S3585 S7169 S6657 S1920 S5504 S3456 S4992 S2944 S6528 S5888 S3840 S7424 S6912 S5760 S3712 S7296 S6784 S7680 S1921 S5505 S3457 S4993 S2945 S6529 S5889 S3841 S7425 S6913 S5761 S3713 S7297 S6785 S7681 S6016 S3968 S7552 S7040 S7936 S7808 S6017 S3969 S7553 S7041 S7937 S7809 S8064 S8065 - setOfArgsP
              T0 T2 T16 T18 - setOfArgsO
              A1 - agent )

    (:init (= (stage) 0)

           (canAssertP a)
           (canAssertP i)
           (canAssertP h)
           (canAssertP k)
           (canAssertP j)
           (canAssertP m)
           (canAssertP l)

           (= (prob-belief A1) 1)

           (= (prob-of-success) 0)

           (successful S1 T0)		; (['a'], [])
           (successful S257 T0)		; (['a', 'i'], [])
           (successful S129 T0)		; (['a', 'h'], [])
           (successful S129 T2)		; (['a', 'h'], ['b'])
           (successful S1025 T0)		; (['a', 'k'], [])
           (successful S1025 T16)		; (['a', 'k'], ['e'])
           (successful S513 T0)		; (['a', 'j'], [])
           (successful S4097 T0)		; (['a', 'm'], [])
           (successful S2049 T0)		; (['a', 'l'], [])
           (successful S385 T0)		; (['a', 'i', 'h'], [])
           (successful S385 T2)		; (['a', 'i', 'h'], ['b'])
           (successful S1281 T0)		; (['a', 'i', 'k'], [])
           (successful S1281 T16)		; (['a', 'i', 'k'], ['e'])
           (successful S769 T0)		; (['a', 'i', 'j'], [])
           (successful S4353 T0)		; (['a', 'i', 'm'], [])
           (successful S2305 T0)		; (['a', 'i', 'l'], [])
           (successful S1153 T0)		; (['a', 'h', 'k'], [])
           (successful S1153 T2)		; (['a', 'h', 'k'], ['b'])
           (successful S1153 T16)		; (['a', 'h', 'k'], ['e'])
           (successful S1153 T18)		; (['a', 'h', 'k'], ['b', 'e'])
           (successful S641 T0)		; (['a', 'h', 'j'], [])
           (successful S641 T2)		; (['a', 'h', 'j'], ['b'])
           (successful S4225 T0)		; (['a', 'h', 'm'], [])
           (successful S2177 T0)		; (['a', 'h', 'l'], [])
           (successful S2177 T2)		; (['a', 'h', 'l'], ['b'])
           (successful S1537 T0)		; (['a', 'k', 'j'], [])
           (successful S5121 T0)		; (['a', 'k', 'm'], [])
           (successful S5121 T16)		; (['a', 'k', 'm'], ['e'])
           (successful S3073 T0)		; (['a', 'k', 'l'], [])
           (successful S3073 T16)		; (['a', 'k', 'l'], ['e'])
           (successful S4609 T0)		; (['a', 'j', 'm'], [])
           (successful S2561 T0)		; (['a', 'j', 'l'], [])
           (successful S6145 T0)		; (['a', 'm', 'l'], [])
           (successful S1409 T0)		; (['a', 'i', 'h', 'k'], [])
           (successful S1409 T2)		; (['a', 'i', 'h', 'k'], ['b'])
           (successful S1409 T16)		; (['a', 'i', 'h', 'k'], ['e'])
           (successful S1409 T18)		; (['a', 'i', 'h', 'k'], ['b', 'e'])
           (successful S897 T0)		; (['a', 'i', 'h', 'j'], [])
           (successful S897 T2)		; (['a', 'i', 'h', 'j'], ['b'])
           (successful S4481 T0)		; (['a', 'i', 'h', 'm'], [])
           (successful S2433 T0)		; (['a', 'i', 'h', 'l'], [])
           (successful S2433 T2)		; (['a', 'i', 'h', 'l'], ['b'])
           (successful S1793 T0)		; (['a', 'i', 'k', 'j'], [])
           (successful S1793 T16)		; (['a', 'i', 'k', 'j'], ['e'])
           (successful S5377 T0)		; (['a', 'i', 'k', 'm'], [])
           (successful S5377 T16)		; (['a', 'i', 'k', 'm'], ['e'])
           (successful S3329 T0)		; (['a', 'i', 'k', 'l'], [])
           (successful S3329 T16)		; (['a', 'i', 'k', 'l'], ['e'])
           (successful S4865 T0)		; (['a', 'i', 'j', 'm'], [])
           (successful S2817 T0)		; (['a', 'i', 'j', 'l'], [])
           (successful S6401 T0)		; (['a', 'i', 'm', 'l'], [])
           (successful S1665 T0)		; (['a', 'h', 'k', 'j'], [])
           (successful S1665 T2)		; (['a', 'h', 'k', 'j'], ['b'])
           (successful S5249 T0)		; (['a', 'h', 'k', 'm'], [])
           (successful S5249 T16)		; (['a', 'h', 'k', 'm'], ['e'])
           (successful S3201 T0)		; (['a', 'h', 'k', 'l'], [])
           (successful S3201 T2)		; (['a', 'h', 'k', 'l'], ['b'])
           (successful S3201 T16)		; (['a', 'h', 'k', 'l'], ['e'])
           (successful S3201 T18)		; (['a', 'h', 'k', 'l'], ['b', 'e'])
           (successful S4737 T0)		; (['a', 'h', 'j', 'm'], [])
           (successful S2689 T0)		; (['a', 'h', 'j', 'l'], [])
           (successful S2689 T2)		; (['a', 'h', 'j', 'l'], ['b'])
           (successful S6273 T0)		; (['a', 'h', 'm', 'l'], [])
           (successful S6273 T2)		; (['a', 'h', 'm', 'l'], ['b'])
           (successful S5633 T0)		; (['a', 'k', 'j', 'm'], [])
           (successful S3585 T0)		; (['a', 'k', 'j', 'l'], [])
           (successful S7169 T0)		; (['a', 'k', 'm', 'l'], [])
           (successful S7169 T16)		; (['a', 'k', 'm', 'l'], ['e'])
           (successful S6657 T0)		; (['a', 'j', 'm', 'l'], [])
           (successful S1921 T0)		; (['a', 'i', 'h', 'k', 'j'], [])
           (successful S1921 T2)		; (['a', 'i', 'h', 'k', 'j'], ['b'])
           (successful S5505 T0)		; (['a', 'i', 'h', 'k', 'm'], [])
           (successful S5505 T16)		; (['a', 'i', 'h', 'k', 'm'], ['e'])
           (successful S3457 T0)		; (['a', 'i', 'h', 'k', 'l'], [])
           (successful S3457 T2)		; (['a', 'i', 'h', 'k', 'l'], ['b'])
           (successful S3457 T16)		; (['a', 'i', 'h', 'k', 'l'], ['e'])
           (successful S3457 T18)		; (['a', 'i', 'h', 'k', 'l'], ['b', 'e'])
           (successful S4993 T0)		; (['a', 'i', 'h', 'j', 'm'], [])
           (successful S2945 T0)		; (['a', 'i', 'h', 'j', 'l'], [])
           (successful S2945 T2)		; (['a', 'i', 'h', 'j', 'l'], ['b'])
           (successful S6529 T0)		; (['a', 'i', 'h', 'm', 'l'], [])
           (successful S6529 T2)		; (['a', 'i', 'h', 'm', 'l'], ['b'])
           (successful S5889 T0)		; (['a', 'i', 'k', 'j', 'm'], [])
           (successful S5889 T16)		; (['a', 'i', 'k', 'j', 'm'], ['e'])
           (successful S3841 T0)		; (['a', 'i', 'k', 'j', 'l'], [])
           (successful S3841 T16)		; (['a', 'i', 'k', 'j', 'l'], ['e'])
           (successful S7425 T0)		; (['a', 'i', 'k', 'm', 'l'], [])
           (successful S7425 T16)		; (['a', 'i', 'k', 'm', 'l'], ['e'])
           (successful S6913 T0)		; (['a', 'i', 'j', 'm', 'l'], [])
           (successful S5761 T0)		; (['a', 'h', 'k', 'j', 'm'], [])
           (successful S3713 T0)		; (['a', 'h', 'k', 'j', 'l'], [])
           (successful S3713 T2)		; (['a', 'h', 'k', 'j', 'l'], ['b'])
           (successful S7297 T0)		; (['a', 'h', 'k', 'm', 'l'], [])
           (successful S7297 T16)		; (['a', 'h', 'k', 'm', 'l'], ['e'])
           (successful S6785 T0)		; (['a', 'h', 'j', 'm', 'l'], [])
           (successful S6785 T2)		; (['a', 'h', 'j', 'm', 'l'], ['b'])
           (successful S7681 T0)		; (['a', 'k', 'j', 'm', 'l'], [])
           (successful S6017 T0)		; (['a', 'i', 'h', 'k', 'j', 'm'], [])
           (successful S6017 T16)		; (['a', 'i', 'h', 'k', 'j', 'm'], ['e'])
           (successful S3969 T0)		; (['a', 'i', 'h', 'k', 'j', 'l'], [])
           (successful S3969 T2)		; (['a', 'i', 'h', 'k', 'j', 'l'], ['b'])
           (successful S7553 T0)		; (['a', 'i', 'h', 'k', 'm', 'l'], [])
           (successful S7553 T16)		; (['a', 'i', 'h', 'k', 'm', 'l'], ['e'])
           (successful S7041 T0)		; (['a', 'i', 'h', 'j', 'm', 'l'], [])
           (successful S7041 T2)		; (['a', 'i', 'h', 'j', 'm', 'l'], ['b'])
           (successful S7937 T0)		; (['a', 'i', 'k', 'j', 'm', 'l'], [])
           (successful S7937 T16)		; (['a', 'i', 'k', 'j', 'm', 'l'], ['e'])
           (successful S7809 T0)		; (['a', 'h', 'k', 'j', 'm', 'l'], [])
           (successful S7809 T2)		; (['a', 'h', 'k', 'j', 'm', 'l'], ['b'])
           (successful S8065 T0)		; (['a', 'i', 'h', 'k', 'j', 'm', 'l'], [])

           (dialogueP S129)
           (dialogueO A1 T18)

           (addP a S0 S1)		; a + [] = ['a']
           (addP a S1 S1)		; a + ['a'] = ['a']
           (addP a S256 S257)		; a + ['i'] = ['i', 'a']
           (addP a S128 S129)		; a + ['h'] = ['a', 'h']
           (addP a S1024 S1025)		; a + ['k'] = ['a', 'k']
           (addP a S512 S513)		; a + ['j'] = ['a', 'j']
           (addP a S4096 S4097)		; a + ['m'] = ['a', 'm']
           (addP a S2048 S2049)		; a + ['l'] = ['a', 'l']
           (addP a S257 S257)		; a + ['a', 'i'] = ['a', 'i']
           (addP a S129 S129)		; a + ['a', 'h'] = ['a', 'h']
           (addP a S1025 S1025)		; a + ['a', 'k'] = ['a', 'k']
           (addP a S513 S513)		; a + ['a', 'j'] = ['a', 'j']
           (addP a S4097 S4097)		; a + ['a', 'm'] = ['a', 'm']
           (addP a S2049 S2049)		; a + ['a', 'l'] = ['a', 'l']
           (addP a S384 S385)		; a + ['i', 'h'] = ['i', 'h', 'a']
           (addP a S1280 S1281)		; a + ['i', 'k'] = ['i', 'a', 'k']
           (addP a S768 S769)		; a + ['i', 'j'] = ['i', 'a', 'j']
           (addP a S4352 S4353)		; a + ['i', 'm'] = ['i', 'a', 'm']
           (addP a S2304 S2305)		; a + ['i', 'l'] = ['i', 'a', 'l']
           (addP a S1152 S1153)		; a + ['h', 'k'] = ['a', 'h', 'k']
           (addP a S640 S641)		; a + ['h', 'j'] = ['a', 'h', 'j']
           (addP a S4224 S4225)		; a + ['h', 'm'] = ['a', 'h', 'm']
           (addP a S2176 S2177)		; a + ['h', 'l'] = ['a', 'h', 'l']
           (addP a S1536 S1537)		; a + ['k', 'j'] = ['a', 'k', 'j']
           (addP a S5120 S5121)		; a + ['k', 'm'] = ['a', 'k', 'm']
           (addP a S3072 S3073)		; a + ['k', 'l'] = ['a', 'k', 'l']
           (addP a S4608 S4609)		; a + ['j', 'm'] = ['a', 'j', 'm']
           (addP a S2560 S2561)		; a + ['j', 'l'] = ['a', 'j', 'l']
           (addP a S6144 S6145)		; a + ['m', 'l'] = ['a', 'm', 'l']
           (addP a S385 S385)		; a + ['a', 'i', 'h'] = ['a', 'i', 'h']
           (addP a S1281 S1281)		; a + ['a', 'i', 'k'] = ['a', 'i', 'k']
           (addP a S769 S769)		; a + ['a', 'i', 'j'] = ['a', 'i', 'j']
           (addP a S4353 S4353)		; a + ['a', 'i', 'm'] = ['a', 'i', 'm']
           (addP a S2305 S2305)		; a + ['a', 'i', 'l'] = ['a', 'i', 'l']
           (addP a S1153 S1153)		; a + ['a', 'h', 'k'] = ['a', 'h', 'k']
           (addP a S641 S641)		; a + ['a', 'h', 'j'] = ['a', 'h', 'j']
           (addP a S4225 S4225)		; a + ['a', 'h', 'm'] = ['a', 'h', 'm']
           (addP a S2177 S2177)		; a + ['a', 'h', 'l'] = ['a', 'h', 'l']
           (addP a S1537 S1537)		; a + ['a', 'k', 'j'] = ['a', 'k', 'j']
           (addP a S5121 S5121)		; a + ['a', 'k', 'm'] = ['a', 'k', 'm']
           (addP a S3073 S3073)		; a + ['a', 'k', 'l'] = ['a', 'k', 'l']
           (addP a S4609 S4609)		; a + ['a', 'j', 'm'] = ['a', 'j', 'm']
           (addP a S2561 S2561)		; a + ['a', 'j', 'l'] = ['a', 'j', 'l']
           (addP a S6145 S6145)		; a + ['a', 'm', 'l'] = ['a', 'm', 'l']
           (addP a S1408 S1409)		; a + ['i', 'h', 'k'] = ['i', 'h', 'k', 'a']
           (addP a S896 S897)		; a + ['i', 'h', 'j'] = ['i', 'h', 'j', 'a']
           (addP a S4480 S4481)		; a + ['i', 'h', 'm'] = ['i', 'h', 'm', 'a']
           (addP a S2432 S2433)		; a + ['i', 'h', 'l'] = ['i', 'h', 'l', 'a']
           (addP a S1792 S1793)		; a + ['i', 'k', 'j'] = ['i', 'a', 'k', 'j']
           (addP a S5376 S5377)		; a + ['i', 'k', 'm'] = ['i', 'a', 'k', 'm']
           (addP a S3328 S3329)		; a + ['i', 'k', 'l'] = ['i', 'a', 'k', 'l']
           (addP a S4864 S4865)		; a + ['i', 'j', 'm'] = ['i', 'a', 'j', 'm']
           (addP a S2816 S2817)		; a + ['i', 'j', 'l'] = ['i', 'a', 'j', 'l']
           (addP a S6400 S6401)		; a + ['i', 'm', 'l'] = ['i', 'a', 'm', 'l']
           (addP a S1664 S1665)		; a + ['h', 'k', 'j'] = ['a', 'h', 'k', 'j']
           (addP a S5248 S5249)		; a + ['h', 'k', 'm'] = ['a', 'h', 'k', 'm']
           (addP a S3200 S3201)		; a + ['h', 'k', 'l'] = ['a', 'h', 'k', 'l']
           (addP a S4736 S4737)		; a + ['h', 'j', 'm'] = ['a', 'h', 'j', 'm']
           (addP a S2688 S2689)		; a + ['h', 'j', 'l'] = ['a', 'h', 'j', 'l']
           (addP a S6272 S6273)		; a + ['h', 'm', 'l'] = ['a', 'h', 'm', 'l']
           (addP a S5632 S5633)		; a + ['k', 'j', 'm'] = ['a', 'k', 'j', 'm']
           (addP a S3584 S3585)		; a + ['k', 'j', 'l'] = ['a', 'k', 'j', 'l']
           (addP a S7168 S7169)		; a + ['k', 'm', 'l'] = ['a', 'k', 'm', 'l']
           (addP a S6656 S6657)		; a + ['j', 'm', 'l'] = ['a', 'j', 'm', 'l']
           (addP a S1409 S1409)		; a + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'h']
           (addP a S897 S897)		; a + ['a', 'i', 'h', 'j'] = ['a', 'i', 'j', 'h']
           (addP a S4481 S4481)		; a + ['a', 'i', 'h', 'm'] = ['a', 'i', 'm', 'h']
           (addP a S2433 S2433)		; a + ['a', 'i', 'h', 'l'] = ['a', 'i', 'l', 'h']
           (addP a S1793 S1793)		; a + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j']
           (addP a S5377 S5377)		; a + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'm']
           (addP a S3329 S3329)		; a + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'l']
           (addP a S4865 S4865)		; a + ['a', 'i', 'j', 'm'] = ['a', 'i', 'j', 'm']
           (addP a S2817 S2817)		; a + ['a', 'i', 'j', 'l'] = ['a', 'i', 'j', 'l']
           (addP a S6401 S6401)		; a + ['a', 'i', 'm', 'l'] = ['a', 'i', 'm', 'l']
           (addP a S1665 S1665)		; a + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j']
           (addP a S5249 S5249)		; a + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'm']
           (addP a S3201 S3201)		; a + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'l']
           (addP a S4737 S4737)		; a + ['a', 'h', 'j', 'm'] = ['a', 'h', 'j', 'm']
           (addP a S2689 S2689)		; a + ['a', 'h', 'j', 'l'] = ['a', 'h', 'j', 'l']
           (addP a S6273 S6273)		; a + ['a', 'h', 'm', 'l'] = ['a', 'h', 'm', 'l']
           (addP a S5633 S5633)		; a + ['a', 'k', 'j', 'm'] = ['a', 'k', 'j', 'm']
           (addP a S3585 S3585)		; a + ['a', 'k', 'j', 'l'] = ['a', 'k', 'j', 'l']
           (addP a S7169 S7169)		; a + ['a', 'k', 'm', 'l'] = ['a', 'k', 'm', 'l']
           (addP a S6657 S6657)		; a + ['a', 'j', 'm', 'l'] = ['a', 'j', 'm', 'l']
           (addP a S1920 S1921)		; a + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j', 'a']
           (addP a S5504 S5505)		; a + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'm', 'a']
           (addP a S3456 S3457)		; a + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'l', 'a']
           (addP a S4992 S4993)		; a + ['i', 'h', 'j', 'm'] = ['i', 'h', 'j', 'm', 'a']
           (addP a S2944 S2945)		; a + ['i', 'h', 'j', 'l'] = ['i', 'h', 'j', 'l', 'a']
           (addP a S6528 S6529)		; a + ['i', 'h', 'm', 'l'] = ['i', 'h', 'm', 'l', 'a']
           (addP a S5888 S5889)		; a + ['i', 'k', 'j', 'm'] = ['i', 'a', 'k', 'j', 'm']
           (addP a S3840 S3841)		; a + ['i', 'k', 'j', 'l'] = ['i', 'a', 'k', 'j', 'l']
           (addP a S7424 S7425)		; a + ['i', 'k', 'm', 'l'] = ['i', 'a', 'k', 'm', 'l']
           (addP a S6912 S6913)		; a + ['i', 'j', 'm', 'l'] = ['i', 'a', 'j', 'm', 'l']
           (addP a S5760 S5761)		; a + ['h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP a S3712 S3713)		; a + ['h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP a S7296 S7297)		; a + ['h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP a S6784 S6785)		; a + ['h', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP a S7680 S7681)		; a + ['k', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP a S1921 S1921)		; a + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j']
           (addP a S5505 S5505)		; a + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'm']
           (addP a S3457 S3457)		; a + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'l']
           (addP a S4993 S4993)		; a + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'j', 'm']
           (addP a S2945 S2945)		; a + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'j', 'l']
           (addP a S6529 S6529)		; a + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'm', 'l']
           (addP a S5889 S5889)		; a + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP a S3841 S3841)		; a + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP a S7425 S7425)		; a + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP a S6913 S6913)		; a + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP a S5761 S5761)		; a + ['a', 'h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP a S3713 S3713)		; a + ['a', 'h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP a S7297 S7297)		; a + ['a', 'h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP a S6785 S6785)		; a + ['a', 'h', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP a S7681 S7681)		; a + ['a', 'k', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP a S6016 S6017)		; a + ['i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP a S3968 S3969)		; a + ['i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP a S7552 S7553)		; a + ['i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP a S7040 S7041)		; a + ['i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP a S7936 S7937)		; a + ['i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP a S7808 S7809)		; a + ['h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP a S6017 S6017)		; a + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP a S3969 S3969)		; a + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP a S7553 S7553)		; a + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP a S7041 S7041)		; a + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP a S7937 S7937)		; a + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP a S7809 S7809)		; a + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP a S8064 S8065)		; a + ['i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP a S8065 S8065)		; a + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP i S0 S256)		; i + [] = ['i']
           (addP i S1 S257)		; i + ['a'] = ['a', 'i']
           (addP i S256 S256)		; i + ['i'] = ['i']
           (addP i S128 S384)		; i + ['h'] = ['i', 'h']
           (addP i S1024 S1280)		; i + ['k'] = ['i', 'k']
           (addP i S512 S768)		; i + ['j'] = ['i', 'j']
           (addP i S4096 S4352)		; i + ['m'] = ['i', 'm']
           (addP i S2048 S2304)		; i + ['l'] = ['i', 'l']
           (addP i S257 S257)		; i + ['a', 'i'] = ['a', 'i']
           (addP i S129 S385)		; i + ['a', 'h'] = ['a', 'h', 'i']
           (addP i S1025 S1281)		; i + ['a', 'k'] = ['a', 'i', 'k']
           (addP i S513 S769)		; i + ['a', 'j'] = ['a', 'i', 'j']
           (addP i S4097 S4353)		; i + ['a', 'm'] = ['a', 'i', 'm']
           (addP i S2049 S2305)		; i + ['a', 'l'] = ['a', 'i', 'l']
           (addP i S384 S384)		; i + ['i', 'h'] = ['i', 'h']
           (addP i S1280 S1280)		; i + ['i', 'k'] = ['i', 'k']
           (addP i S768 S768)		; i + ['i', 'j'] = ['i', 'j']
           (addP i S4352 S4352)		; i + ['i', 'm'] = ['i', 'm']
           (addP i S2304 S2304)		; i + ['i', 'l'] = ['i', 'l']
           (addP i S1152 S1408)		; i + ['h', 'k'] = ['i', 'h', 'k']
           (addP i S640 S896)		; i + ['h', 'j'] = ['i', 'h', 'j']
           (addP i S4224 S4480)		; i + ['h', 'm'] = ['i', 'h', 'm']
           (addP i S2176 S2432)		; i + ['h', 'l'] = ['i', 'h', 'l']
           (addP i S1536 S1792)		; i + ['k', 'j'] = ['i', 'k', 'j']
           (addP i S5120 S5376)		; i + ['k', 'm'] = ['i', 'k', 'm']
           (addP i S3072 S3328)		; i + ['k', 'l'] = ['i', 'k', 'l']
           (addP i S4608 S4864)		; i + ['j', 'm'] = ['i', 'j', 'm']
           (addP i S2560 S2816)		; i + ['j', 'l'] = ['i', 'j', 'l']
           (addP i S6144 S6400)		; i + ['m', 'l'] = ['i', 'm', 'l']
           (addP i S385 S385)		; i + ['a', 'i', 'h'] = ['a', 'i', 'h']
           (addP i S1281 S1281)		; i + ['a', 'i', 'k'] = ['a', 'i', 'k']
           (addP i S769 S769)		; i + ['a', 'i', 'j'] = ['a', 'i', 'j']
           (addP i S4353 S4353)		; i + ['a', 'i', 'm'] = ['a', 'i', 'm']
           (addP i S2305 S2305)		; i + ['a', 'i', 'l'] = ['a', 'i', 'l']
           (addP i S1153 S1409)		; i + ['a', 'h', 'k'] = ['a', 'h', 'k', 'i']
           (addP i S641 S897)		; i + ['a', 'h', 'j'] = ['a', 'h', 'j', 'i']
           (addP i S4225 S4481)		; i + ['a', 'h', 'm'] = ['a', 'h', 'm', 'i']
           (addP i S2177 S2433)		; i + ['a', 'h', 'l'] = ['a', 'h', 'i', 'l']
           (addP i S1537 S1793)		; i + ['a', 'k', 'j'] = ['a', 'i', 'k', 'j']
           (addP i S5121 S5377)		; i + ['a', 'k', 'm'] = ['a', 'i', 'k', 'm']
           (addP i S3073 S3329)		; i + ['a', 'k', 'l'] = ['a', 'i', 'k', 'l']
           (addP i S4609 S4865)		; i + ['a', 'j', 'm'] = ['a', 'i', 'j', 'm']
           (addP i S2561 S2817)		; i + ['a', 'j', 'l'] = ['a', 'i', 'j', 'l']
           (addP i S6145 S6401)		; i + ['a', 'm', 'l'] = ['a', 'i', 'm', 'l']
           (addP i S1408 S1408)		; i + ['i', 'h', 'k'] = ['i', 'h', 'k']
           (addP i S896 S896)		; i + ['i', 'h', 'j'] = ['i', 'h', 'j']
           (addP i S4480 S4480)		; i + ['i', 'h', 'm'] = ['i', 'h', 'm']
           (addP i S2432 S2432)		; i + ['i', 'h', 'l'] = ['i', 'h', 'l']
           (addP i S1792 S1792)		; i + ['i', 'k', 'j'] = ['i', 'k', 'j']
           (addP i S5376 S5376)		; i + ['i', 'k', 'm'] = ['i', 'k', 'm']
           (addP i S3328 S3328)		; i + ['i', 'k', 'l'] = ['i', 'k', 'l']
           (addP i S4864 S4864)		; i + ['i', 'j', 'm'] = ['i', 'j', 'm']
           (addP i S2816 S2816)		; i + ['i', 'j', 'l'] = ['i', 'j', 'l']
           (addP i S6400 S6400)		; i + ['i', 'm', 'l'] = ['i', 'm', 'l']
           (addP i S1664 S1920)		; i + ['h', 'k', 'j'] = ['i', 'h', 'k', 'j']
           (addP i S5248 S5504)		; i + ['h', 'k', 'm'] = ['i', 'h', 'k', 'm']
           (addP i S3200 S3456)		; i + ['h', 'k', 'l'] = ['i', 'h', 'k', 'l']
           (addP i S4736 S4992)		; i + ['h', 'j', 'm'] = ['i', 'h', 'j', 'm']
           (addP i S2688 S2944)		; i + ['h', 'j', 'l'] = ['i', 'h', 'j', 'l']
           (addP i S6272 S6528)		; i + ['h', 'm', 'l'] = ['i', 'h', 'm', 'l']
           (addP i S5632 S5888)		; i + ['k', 'j', 'm'] = ['i', 'k', 'j', 'm']
           (addP i S3584 S3840)		; i + ['k', 'j', 'l'] = ['i', 'k', 'j', 'l']
           (addP i S7168 S7424)		; i + ['k', 'm', 'l'] = ['i', 'k', 'm', 'l']
           (addP i S6656 S6912)		; i + ['j', 'm', 'l'] = ['i', 'j', 'm', 'l']
           (addP i S1409 S1409)		; i + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'h']
           (addP i S897 S897)		; i + ['a', 'i', 'h', 'j'] = ['a', 'i', 'j', 'h']
           (addP i S4481 S4481)		; i + ['a', 'i', 'h', 'm'] = ['a', 'i', 'm', 'h']
           (addP i S2433 S2433)		; i + ['a', 'i', 'h', 'l'] = ['a', 'i', 'l', 'h']
           (addP i S1793 S1793)		; i + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j']
           (addP i S5377 S5377)		; i + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'm']
           (addP i S3329 S3329)		; i + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'l']
           (addP i S4865 S4865)		; i + ['a', 'i', 'j', 'm'] = ['a', 'i', 'j', 'm']
           (addP i S2817 S2817)		; i + ['a', 'i', 'j', 'l'] = ['a', 'i', 'j', 'l']
           (addP i S6401 S6401)		; i + ['a', 'i', 'm', 'l'] = ['a', 'i', 'm', 'l']
           (addP i S1665 S1921)		; i + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j', 'i']
           (addP i S5249 S5505)		; i + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'm', 'i']
           (addP i S3201 S3457)		; i + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'i', 'l']
           (addP i S4737 S4993)		; i + ['a', 'h', 'j', 'm'] = ['a', 'h', 'j', 'm', 'i']
           (addP i S2689 S2945)		; i + ['a', 'h', 'j', 'l'] = ['a', 'h', 'j', 'l', 'i']
           (addP i S6273 S6529)		; i + ['a', 'h', 'm', 'l'] = ['a', 'h', 'i', 'm', 'l']
           (addP i S5633 S5889)		; i + ['a', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP i S3585 S3841)		; i + ['a', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP i S7169 S7425)		; i + ['a', 'k', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP i S6657 S6913)		; i + ['a', 'j', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP i S1920 S1920)		; i + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j']
           (addP i S5504 S5504)		; i + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'm']
           (addP i S3456 S3456)		; i + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'l']
           (addP i S4992 S4992)		; i + ['i', 'h', 'j', 'm'] = ['i', 'h', 'j', 'm']
           (addP i S2944 S2944)		; i + ['i', 'h', 'j', 'l'] = ['i', 'h', 'j', 'l']
           (addP i S6528 S6528)		; i + ['i', 'h', 'm', 'l'] = ['i', 'h', 'm', 'l']
           (addP i S5888 S5888)		; i + ['i', 'k', 'j', 'm'] = ['i', 'k', 'j', 'm']
           (addP i S3840 S3840)		; i + ['i', 'k', 'j', 'l'] = ['i', 'k', 'j', 'l']
           (addP i S7424 S7424)		; i + ['i', 'k', 'm', 'l'] = ['i', 'k', 'm', 'l']
           (addP i S6912 S6912)		; i + ['i', 'j', 'm', 'l'] = ['i', 'j', 'm', 'l']
           (addP i S5760 S6016)		; i + ['h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP i S3712 S3968)		; i + ['h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP i S7296 S7552)		; i + ['h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP i S6784 S7040)		; i + ['h', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP i S7680 S7936)		; i + ['k', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP i S1921 S1921)		; i + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j']
           (addP i S5505 S5505)		; i + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'm']
           (addP i S3457 S3457)		; i + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'l']
           (addP i S4993 S4993)		; i + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'j', 'm']
           (addP i S2945 S2945)		; i + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'j', 'l']
           (addP i S6529 S6529)		; i + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'm', 'l']
           (addP i S5889 S5889)		; i + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP i S3841 S3841)		; i + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP i S7425 S7425)		; i + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP i S6913 S6913)		; i + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP i S5761 S6017)		; i + ['a', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP i S3713 S3969)		; i + ['a', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP i S7297 S7553)		; i + ['a', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP i S6785 S7041)		; i + ['a', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP i S7681 S7937)		; i + ['a', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP i S6016 S6016)		; i + ['i', 'h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP i S3968 S3968)		; i + ['i', 'h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP i S7552 S7552)		; i + ['i', 'h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP i S7040 S7040)		; i + ['i', 'h', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP i S7936 S7936)		; i + ['i', 'k', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP i S7808 S8064)		; i + ['h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP i S6017 S6017)		; i + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP i S3969 S3969)		; i + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP i S7553 S7553)		; i + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP i S7041 S7041)		; i + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP i S7937 S7937)		; i + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP i S7809 S8065)		; i + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP i S8064 S8064)		; i + ['i', 'h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP i S8065 S8065)		; i + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP h S0 S128)		; h + [] = ['h']
           (addP h S1 S129)		; h + ['a'] = ['a', 'h']
           (addP h S256 S384)		; h + ['i'] = ['i', 'h']
           (addP h S128 S128)		; h + ['h'] = ['h']
           (addP h S1024 S1152)		; h + ['k'] = ['h', 'k']
           (addP h S512 S640)		; h + ['j'] = ['h', 'j']
           (addP h S4096 S4224)		; h + ['m'] = ['h', 'm']
           (addP h S2048 S2176)		; h + ['l'] = ['h', 'l']
           (addP h S257 S385)		; h + ['a', 'i'] = ['a', 'i', 'h']
           (addP h S129 S129)		; h + ['a', 'h'] = ['a', 'h']
           (addP h S1025 S1153)		; h + ['a', 'k'] = ['a', 'h', 'k']
           (addP h S513 S641)		; h + ['a', 'j'] = ['a', 'h', 'j']
           (addP h S4097 S4225)		; h + ['a', 'm'] = ['a', 'h', 'm']
           (addP h S2049 S2177)		; h + ['a', 'l'] = ['a', 'h', 'l']
           (addP h S384 S384)		; h + ['i', 'h'] = ['i', 'h']
           (addP h S1280 S1408)		; h + ['i', 'k'] = ['i', 'h', 'k']
           (addP h S768 S896)		; h + ['i', 'j'] = ['i', 'h', 'j']
           (addP h S4352 S4480)		; h + ['i', 'm'] = ['i', 'h', 'm']
           (addP h S2304 S2432)		; h + ['i', 'l'] = ['i', 'h', 'l']
           (addP h S1152 S1152)		; h + ['h', 'k'] = ['h', 'k']
           (addP h S640 S640)		; h + ['h', 'j'] = ['h', 'j']
           (addP h S4224 S4224)		; h + ['h', 'm'] = ['h', 'm']
           (addP h S2176 S2176)		; h + ['h', 'l'] = ['h', 'l']
           (addP h S1536 S1664)		; h + ['k', 'j'] = ['h', 'k', 'j']
           (addP h S5120 S5248)		; h + ['k', 'm'] = ['h', 'k', 'm']
           (addP h S3072 S3200)		; h + ['k', 'l'] = ['h', 'k', 'l']
           (addP h S4608 S4736)		; h + ['j', 'm'] = ['h', 'j', 'm']
           (addP h S2560 S2688)		; h + ['j', 'l'] = ['h', 'j', 'l']
           (addP h S6144 S6272)		; h + ['m', 'l'] = ['h', 'm', 'l']
           (addP h S385 S385)		; h + ['a', 'i', 'h'] = ['a', 'i', 'h']
           (addP h S1281 S1409)		; h + ['a', 'i', 'k'] = ['a', 'i', 'k', 'h']
           (addP h S769 S897)		; h + ['a', 'i', 'j'] = ['a', 'i', 'j', 'h']
           (addP h S4353 S4481)		; h + ['a', 'i', 'm'] = ['a', 'i', 'm', 'h']
           (addP h S2305 S2433)		; h + ['a', 'i', 'l'] = ['a', 'i', 'l', 'h']
           (addP h S1153 S1153)		; h + ['a', 'h', 'k'] = ['a', 'h', 'k']
           (addP h S641 S641)		; h + ['a', 'h', 'j'] = ['a', 'h', 'j']
           (addP h S4225 S4225)		; h + ['a', 'h', 'm'] = ['a', 'h', 'm']
           (addP h S2177 S2177)		; h + ['a', 'h', 'l'] = ['a', 'h', 'l']
           (addP h S1537 S1665)		; h + ['a', 'k', 'j'] = ['a', 'h', 'k', 'j']
           (addP h S5121 S5249)		; h + ['a', 'k', 'm'] = ['a', 'h', 'k', 'm']
           (addP h S3073 S3201)		; h + ['a', 'k', 'l'] = ['a', 'h', 'k', 'l']
           (addP h S4609 S4737)		; h + ['a', 'j', 'm'] = ['a', 'h', 'j', 'm']
           (addP h S2561 S2689)		; h + ['a', 'j', 'l'] = ['a', 'h', 'j', 'l']
           (addP h S6145 S6273)		; h + ['a', 'm', 'l'] = ['a', 'h', 'm', 'l']
           (addP h S1408 S1408)		; h + ['i', 'h', 'k'] = ['i', 'h', 'k']
           (addP h S896 S896)		; h + ['i', 'h', 'j'] = ['i', 'h', 'j']
           (addP h S4480 S4480)		; h + ['i', 'h', 'm'] = ['i', 'h', 'm']
           (addP h S2432 S2432)		; h + ['i', 'h', 'l'] = ['i', 'h', 'l']
           (addP h S1792 S1920)		; h + ['i', 'k', 'j'] = ['i', 'h', 'k', 'j']
           (addP h S5376 S5504)		; h + ['i', 'k', 'm'] = ['i', 'h', 'k', 'm']
           (addP h S3328 S3456)		; h + ['i', 'k', 'l'] = ['i', 'h', 'k', 'l']
           (addP h S4864 S4992)		; h + ['i', 'j', 'm'] = ['i', 'h', 'j', 'm']
           (addP h S2816 S2944)		; h + ['i', 'j', 'l'] = ['i', 'h', 'j', 'l']
           (addP h S6400 S6528)		; h + ['i', 'm', 'l'] = ['i', 'h', 'm', 'l']
           (addP h S1664 S1664)		; h + ['h', 'k', 'j'] = ['h', 'k', 'j']
           (addP h S5248 S5248)		; h + ['h', 'k', 'm'] = ['h', 'k', 'm']
           (addP h S3200 S3200)		; h + ['h', 'k', 'l'] = ['h', 'k', 'l']
           (addP h S4736 S4736)		; h + ['h', 'j', 'm'] = ['h', 'j', 'm']
           (addP h S2688 S2688)		; h + ['h', 'j', 'l'] = ['h', 'j', 'l']
           (addP h S6272 S6272)		; h + ['h', 'm', 'l'] = ['h', 'm', 'l']
           (addP h S5632 S5760)		; h + ['k', 'j', 'm'] = ['h', 'k', 'j', 'm']
           (addP h S3584 S3712)		; h + ['k', 'j', 'l'] = ['h', 'k', 'j', 'l']
           (addP h S7168 S7296)		; h + ['k', 'm', 'l'] = ['h', 'k', 'm', 'l']
           (addP h S6656 S6784)		; h + ['j', 'm', 'l'] = ['h', 'j', 'm', 'l']
           (addP h S1409 S1409)		; h + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'h']
           (addP h S897 S897)		; h + ['a', 'i', 'h', 'j'] = ['a', 'i', 'j', 'h']
           (addP h S4481 S4481)		; h + ['a', 'i', 'h', 'm'] = ['a', 'i', 'm', 'h']
           (addP h S2433 S2433)		; h + ['a', 'i', 'h', 'l'] = ['a', 'i', 'l', 'h']
           (addP h S1793 S1921)		; h + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j', 'h']
           (addP h S5377 S5505)		; h + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'm', 'h']
           (addP h S3329 S3457)		; h + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'l', 'h']
           (addP h S4865 S4993)		; h + ['a', 'i', 'j', 'm'] = ['a', 'i', 'j', 'm', 'h']
           (addP h S2817 S2945)		; h + ['a', 'i', 'j', 'l'] = ['a', 'i', 'j', 'l', 'h']
           (addP h S6401 S6529)		; h + ['a', 'i', 'm', 'l'] = ['a', 'i', 'm', 'l', 'h']
           (addP h S1665 S1665)		; h + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j']
           (addP h S5249 S5249)		; h + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'm']
           (addP h S3201 S3201)		; h + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'l']
           (addP h S4737 S4737)		; h + ['a', 'h', 'j', 'm'] = ['a', 'h', 'j', 'm']
           (addP h S2689 S2689)		; h + ['a', 'h', 'j', 'l'] = ['a', 'h', 'j', 'l']
           (addP h S6273 S6273)		; h + ['a', 'h', 'm', 'l'] = ['a', 'h', 'm', 'l']
           (addP h S5633 S5761)		; h + ['a', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP h S3585 S3713)		; h + ['a', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP h S7169 S7297)		; h + ['a', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP h S6657 S6785)		; h + ['a', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP h S1920 S1920)		; h + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j']
           (addP h S5504 S5504)		; h + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'm']
           (addP h S3456 S3456)		; h + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'l']
           (addP h S4992 S4992)		; h + ['i', 'h', 'j', 'm'] = ['i', 'h', 'j', 'm']
           (addP h S2944 S2944)		; h + ['i', 'h', 'j', 'l'] = ['i', 'h', 'j', 'l']
           (addP h S6528 S6528)		; h + ['i', 'h', 'm', 'l'] = ['i', 'h', 'm', 'l']
           (addP h S5888 S6016)		; h + ['i', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP h S3840 S3968)		; h + ['i', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP h S7424 S7552)		; h + ['i', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP h S6912 S7040)		; h + ['i', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP h S5760 S5760)		; h + ['h', 'k', 'j', 'm'] = ['h', 'k', 'j', 'm']
           (addP h S3712 S3712)		; h + ['h', 'k', 'j', 'l'] = ['h', 'k', 'j', 'l']
           (addP h S7296 S7296)		; h + ['h', 'k', 'm', 'l'] = ['h', 'k', 'm', 'l']
           (addP h S6784 S6784)		; h + ['h', 'j', 'm', 'l'] = ['h', 'j', 'm', 'l']
           (addP h S7680 S7808)		; h + ['k', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP h S1921 S1921)		; h + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j']
           (addP h S5505 S5505)		; h + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'm']
           (addP h S3457 S3457)		; h + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'l']
           (addP h S4993 S4993)		; h + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'j', 'm']
           (addP h S2945 S2945)		; h + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'j', 'l']
           (addP h S6529 S6529)		; h + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'm', 'l']
           (addP h S5889 S6017)		; h + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP h S3841 S3969)		; h + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP h S7425 S7553)		; h + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP h S6913 S7041)		; h + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP h S5761 S5761)		; h + ['a', 'h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP h S3713 S3713)		; h + ['a', 'h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP h S7297 S7297)		; h + ['a', 'h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP h S6785 S6785)		; h + ['a', 'h', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP h S7681 S7809)		; h + ['a', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP h S6016 S6016)		; h + ['i', 'h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP h S3968 S3968)		; h + ['i', 'h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP h S7552 S7552)		; h + ['i', 'h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP h S7040 S7040)		; h + ['i', 'h', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP h S7936 S8064)		; h + ['i', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP h S7808 S7808)		; h + ['h', 'k', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP h S6017 S6017)		; h + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP h S3969 S3969)		; h + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP h S7553 S7553)		; h + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP h S7041 S7041)		; h + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP h S7937 S8065)		; h + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP h S7809 S7809)		; h + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP h S8064 S8064)		; h + ['i', 'h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP h S8065 S8065)		; h + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP k S0 S1024)		; k + [] = ['k']
           (addP k S1 S1025)		; k + ['a'] = ['a', 'k']
           (addP k S256 S1280)		; k + ['i'] = ['i', 'k']
           (addP k S128 S1152)		; k + ['h'] = ['h', 'k']
           (addP k S1024 S1024)		; k + ['k'] = ['k']
           (addP k S512 S1536)		; k + ['j'] = ['k', 'j']
           (addP k S4096 S5120)		; k + ['m'] = ['k', 'm']
           (addP k S2048 S3072)		; k + ['l'] = ['k', 'l']
           (addP k S257 S1281)		; k + ['a', 'i'] = ['a', 'i', 'k']
           (addP k S129 S1153)		; k + ['a', 'h'] = ['a', 'h', 'k']
           (addP k S1025 S1025)		; k + ['a', 'k'] = ['a', 'k']
           (addP k S513 S1537)		; k + ['a', 'j'] = ['a', 'k', 'j']
           (addP k S4097 S5121)		; k + ['a', 'm'] = ['a', 'k', 'm']
           (addP k S2049 S3073)		; k + ['a', 'l'] = ['a', 'k', 'l']
           (addP k S384 S1408)		; k + ['i', 'h'] = ['i', 'h', 'k']
           (addP k S1280 S1280)		; k + ['i', 'k'] = ['i', 'k']
           (addP k S768 S1792)		; k + ['i', 'j'] = ['i', 'k', 'j']
           (addP k S4352 S5376)		; k + ['i', 'm'] = ['i', 'k', 'm']
           (addP k S2304 S3328)		; k + ['i', 'l'] = ['i', 'k', 'l']
           (addP k S1152 S1152)		; k + ['h', 'k'] = ['h', 'k']
           (addP k S640 S1664)		; k + ['h', 'j'] = ['h', 'k', 'j']
           (addP k S4224 S5248)		; k + ['h', 'm'] = ['h', 'k', 'm']
           (addP k S2176 S3200)		; k + ['h', 'l'] = ['h', 'k', 'l']
           (addP k S1536 S1536)		; k + ['k', 'j'] = ['k', 'j']
           (addP k S5120 S5120)		; k + ['k', 'm'] = ['k', 'm']
           (addP k S3072 S3072)		; k + ['k', 'l'] = ['k', 'l']
           (addP k S4608 S5632)		; k + ['j', 'm'] = ['k', 'j', 'm']
           (addP k S2560 S3584)		; k + ['j', 'l'] = ['k', 'j', 'l']
           (addP k S6144 S7168)		; k + ['m', 'l'] = ['k', 'm', 'l']
           (addP k S385 S1409)		; k + ['a', 'i', 'h'] = ['a', 'i', 'k', 'h']
           (addP k S1281 S1281)		; k + ['a', 'i', 'k'] = ['a', 'i', 'k']
           (addP k S769 S1793)		; k + ['a', 'i', 'j'] = ['a', 'i', 'k', 'j']
           (addP k S4353 S5377)		; k + ['a', 'i', 'm'] = ['a', 'i', 'k', 'm']
           (addP k S2305 S3329)		; k + ['a', 'i', 'l'] = ['a', 'i', 'k', 'l']
           (addP k S1153 S1153)		; k + ['a', 'h', 'k'] = ['a', 'h', 'k']
           (addP k S641 S1665)		; k + ['a', 'h', 'j'] = ['a', 'h', 'k', 'j']
           (addP k S4225 S5249)		; k + ['a', 'h', 'm'] = ['a', 'h', 'k', 'm']
           (addP k S2177 S3201)		; k + ['a', 'h', 'l'] = ['a', 'h', 'k', 'l']
           (addP k S1537 S1537)		; k + ['a', 'k', 'j'] = ['a', 'k', 'j']
           (addP k S5121 S5121)		; k + ['a', 'k', 'm'] = ['a', 'k', 'm']
           (addP k S3073 S3073)		; k + ['a', 'k', 'l'] = ['a', 'k', 'l']
           (addP k S4609 S5633)		; k + ['a', 'j', 'm'] = ['a', 'k', 'j', 'm']
           (addP k S2561 S3585)		; k + ['a', 'j', 'l'] = ['a', 'k', 'j', 'l']
           (addP k S6145 S7169)		; k + ['a', 'm', 'l'] = ['a', 'k', 'm', 'l']
           (addP k S1408 S1408)		; k + ['i', 'h', 'k'] = ['i', 'h', 'k']
           (addP k S896 S1920)		; k + ['i', 'h', 'j'] = ['i', 'h', 'k', 'j']
           (addP k S4480 S5504)		; k + ['i', 'h', 'm'] = ['i', 'h', 'k', 'm']
           (addP k S2432 S3456)		; k + ['i', 'h', 'l'] = ['i', 'h', 'k', 'l']
           (addP k S1792 S1792)		; k + ['i', 'k', 'j'] = ['i', 'k', 'j']
           (addP k S5376 S5376)		; k + ['i', 'k', 'm'] = ['i', 'k', 'm']
           (addP k S3328 S3328)		; k + ['i', 'k', 'l'] = ['i', 'k', 'l']
           (addP k S4864 S5888)		; k + ['i', 'j', 'm'] = ['i', 'k', 'j', 'm']
           (addP k S2816 S3840)		; k + ['i', 'j', 'l'] = ['i', 'k', 'j', 'l']
           (addP k S6400 S7424)		; k + ['i', 'm', 'l'] = ['i', 'k', 'm', 'l']
           (addP k S1664 S1664)		; k + ['h', 'k', 'j'] = ['h', 'k', 'j']
           (addP k S5248 S5248)		; k + ['h', 'k', 'm'] = ['h', 'k', 'm']
           (addP k S3200 S3200)		; k + ['h', 'k', 'l'] = ['h', 'k', 'l']
           (addP k S4736 S5760)		; k + ['h', 'j', 'm'] = ['h', 'k', 'j', 'm']
           (addP k S2688 S3712)		; k + ['h', 'j', 'l'] = ['h', 'k', 'j', 'l']
           (addP k S6272 S7296)		; k + ['h', 'm', 'l'] = ['h', 'k', 'm', 'l']
           (addP k S5632 S5632)		; k + ['k', 'j', 'm'] = ['k', 'j', 'm']
           (addP k S3584 S3584)		; k + ['k', 'j', 'l'] = ['k', 'j', 'l']
           (addP k S7168 S7168)		; k + ['k', 'm', 'l'] = ['k', 'm', 'l']
           (addP k S6656 S7680)		; k + ['j', 'm', 'l'] = ['k', 'j', 'm', 'l']
           (addP k S1409 S1409)		; k + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'h']
           (addP k S897 S1921)		; k + ['a', 'i', 'h', 'j'] = ['a', 'i', 'k', 'j', 'h']
           (addP k S4481 S5505)		; k + ['a', 'i', 'h', 'm'] = ['a', 'i', 'k', 'm', 'h']
           (addP k S2433 S3457)		; k + ['a', 'i', 'h', 'l'] = ['a', 'i', 'k', 'l', 'h']
           (addP k S1793 S1793)		; k + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j']
           (addP k S5377 S5377)		; k + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'm']
           (addP k S3329 S3329)		; k + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'l']
           (addP k S4865 S5889)		; k + ['a', 'i', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP k S2817 S3841)		; k + ['a', 'i', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP k S6401 S7425)		; k + ['a', 'i', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP k S1665 S1665)		; k + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j']
           (addP k S5249 S5249)		; k + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'm']
           (addP k S3201 S3201)		; k + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'l']
           (addP k S4737 S5761)		; k + ['a', 'h', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP k S2689 S3713)		; k + ['a', 'h', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP k S6273 S7297)		; k + ['a', 'h', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP k S5633 S5633)		; k + ['a', 'k', 'j', 'm'] = ['a', 'k', 'j', 'm']
           (addP k S3585 S3585)		; k + ['a', 'k', 'j', 'l'] = ['a', 'k', 'j', 'l']
           (addP k S7169 S7169)		; k + ['a', 'k', 'm', 'l'] = ['a', 'k', 'm', 'l']
           (addP k S6657 S7681)		; k + ['a', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP k S1920 S1920)		; k + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j']
           (addP k S5504 S5504)		; k + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'm']
           (addP k S3456 S3456)		; k + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'l']
           (addP k S4992 S6016)		; k + ['i', 'h', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP k S2944 S3968)		; k + ['i', 'h', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP k S6528 S7552)		; k + ['i', 'h', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP k S5888 S5888)		; k + ['i', 'k', 'j', 'm'] = ['i', 'k', 'j', 'm']
           (addP k S3840 S3840)		; k + ['i', 'k', 'j', 'l'] = ['i', 'k', 'j', 'l']
           (addP k S7424 S7424)		; k + ['i', 'k', 'm', 'l'] = ['i', 'k', 'm', 'l']
           (addP k S6912 S7936)		; k + ['i', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP k S5760 S5760)		; k + ['h', 'k', 'j', 'm'] = ['h', 'k', 'j', 'm']
           (addP k S3712 S3712)		; k + ['h', 'k', 'j', 'l'] = ['h', 'k', 'j', 'l']
           (addP k S7296 S7296)		; k + ['h', 'k', 'm', 'l'] = ['h', 'k', 'm', 'l']
           (addP k S6784 S7808)		; k + ['h', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP k S7680 S7680)		; k + ['k', 'j', 'm', 'l'] = ['k', 'j', 'm', 'l']
           (addP k S1921 S1921)		; k + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j']
           (addP k S5505 S5505)		; k + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'm']
           (addP k S3457 S3457)		; k + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'l']
           (addP k S4993 S6017)		; k + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP k S2945 S3969)		; k + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP k S6529 S7553)		; k + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP k S5889 S5889)		; k + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP k S3841 S3841)		; k + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP k S7425 S7425)		; k + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP k S6913 S7937)		; k + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP k S5761 S5761)		; k + ['a', 'h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP k S3713 S3713)		; k + ['a', 'h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP k S7297 S7297)		; k + ['a', 'h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP k S6785 S7809)		; k + ['a', 'h', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP k S7681 S7681)		; k + ['a', 'k', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP k S6016 S6016)		; k + ['i', 'h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP k S3968 S3968)		; k + ['i', 'h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP k S7552 S7552)		; k + ['i', 'h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP k S7040 S8064)		; k + ['i', 'h', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP k S7936 S7936)		; k + ['i', 'k', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP k S7808 S7808)		; k + ['h', 'k', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP k S6017 S6017)		; k + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP k S3969 S3969)		; k + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP k S7553 S7553)		; k + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP k S7041 S8065)		; k + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP k S7937 S7937)		; k + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP k S7809 S7809)		; k + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP k S8064 S8064)		; k + ['i', 'h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP k S8065 S8065)		; k + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP j S0 S512)		; j + [] = ['j']
           (addP j S1 S513)		; j + ['a'] = ['a', 'j']
           (addP j S256 S768)		; j + ['i'] = ['i', 'j']
           (addP j S128 S640)		; j + ['h'] = ['h', 'j']
           (addP j S1024 S1536)		; j + ['k'] = ['k', 'j']
           (addP j S512 S512)		; j + ['j'] = ['j']
           (addP j S4096 S4608)		; j + ['m'] = ['j', 'm']
           (addP j S2048 S2560)		; j + ['l'] = ['j', 'l']
           (addP j S257 S769)		; j + ['a', 'i'] = ['a', 'i', 'j']
           (addP j S129 S641)		; j + ['a', 'h'] = ['a', 'h', 'j']
           (addP j S1025 S1537)		; j + ['a', 'k'] = ['a', 'k', 'j']
           (addP j S513 S513)		; j + ['a', 'j'] = ['a', 'j']
           (addP j S4097 S4609)		; j + ['a', 'm'] = ['a', 'j', 'm']
           (addP j S2049 S2561)		; j + ['a', 'l'] = ['a', 'j', 'l']
           (addP j S384 S896)		; j + ['i', 'h'] = ['i', 'h', 'j']
           (addP j S1280 S1792)		; j + ['i', 'k'] = ['i', 'k', 'j']
           (addP j S768 S768)		; j + ['i', 'j'] = ['i', 'j']
           (addP j S4352 S4864)		; j + ['i', 'm'] = ['i', 'j', 'm']
           (addP j S2304 S2816)		; j + ['i', 'l'] = ['i', 'j', 'l']
           (addP j S1152 S1664)		; j + ['h', 'k'] = ['h', 'k', 'j']
           (addP j S640 S640)		; j + ['h', 'j'] = ['h', 'j']
           (addP j S4224 S4736)		; j + ['h', 'm'] = ['h', 'j', 'm']
           (addP j S2176 S2688)		; j + ['h', 'l'] = ['h', 'j', 'l']
           (addP j S1536 S1536)		; j + ['k', 'j'] = ['k', 'j']
           (addP j S5120 S5632)		; j + ['k', 'm'] = ['k', 'j', 'm']
           (addP j S3072 S3584)		; j + ['k', 'l'] = ['k', 'j', 'l']
           (addP j S4608 S4608)		; j + ['j', 'm'] = ['j', 'm']
           (addP j S2560 S2560)		; j + ['j', 'l'] = ['j', 'l']
           (addP j S6144 S6656)		; j + ['m', 'l'] = ['j', 'm', 'l']
           (addP j S385 S897)		; j + ['a', 'i', 'h'] = ['a', 'i', 'j', 'h']
           (addP j S1281 S1793)		; j + ['a', 'i', 'k'] = ['a', 'i', 'k', 'j']
           (addP j S769 S769)		; j + ['a', 'i', 'j'] = ['a', 'i', 'j']
           (addP j S4353 S4865)		; j + ['a', 'i', 'm'] = ['a', 'i', 'j', 'm']
           (addP j S2305 S2817)		; j + ['a', 'i', 'l'] = ['a', 'i', 'j', 'l']
           (addP j S1153 S1665)		; j + ['a', 'h', 'k'] = ['a', 'h', 'k', 'j']
           (addP j S641 S641)		; j + ['a', 'h', 'j'] = ['a', 'h', 'j']
           (addP j S4225 S4737)		; j + ['a', 'h', 'm'] = ['a', 'h', 'j', 'm']
           (addP j S2177 S2689)		; j + ['a', 'h', 'l'] = ['a', 'h', 'j', 'l']
           (addP j S1537 S1537)		; j + ['a', 'k', 'j'] = ['a', 'k', 'j']
           (addP j S5121 S5633)		; j + ['a', 'k', 'm'] = ['a', 'k', 'j', 'm']
           (addP j S3073 S3585)		; j + ['a', 'k', 'l'] = ['a', 'k', 'j', 'l']
           (addP j S4609 S4609)		; j + ['a', 'j', 'm'] = ['a', 'j', 'm']
           (addP j S2561 S2561)		; j + ['a', 'j', 'l'] = ['a', 'j', 'l']
           (addP j S6145 S6657)		; j + ['a', 'm', 'l'] = ['a', 'j', 'm', 'l']
           (addP j S1408 S1920)		; j + ['i', 'h', 'k'] = ['i', 'h', 'k', 'j']
           (addP j S896 S896)		; j + ['i', 'h', 'j'] = ['i', 'h', 'j']
           (addP j S4480 S4992)		; j + ['i', 'h', 'm'] = ['i', 'h', 'j', 'm']
           (addP j S2432 S2944)		; j + ['i', 'h', 'l'] = ['i', 'h', 'j', 'l']
           (addP j S1792 S1792)		; j + ['i', 'k', 'j'] = ['i', 'k', 'j']
           (addP j S5376 S5888)		; j + ['i', 'k', 'm'] = ['i', 'k', 'j', 'm']
           (addP j S3328 S3840)		; j + ['i', 'k', 'l'] = ['i', 'k', 'j', 'l']
           (addP j S4864 S4864)		; j + ['i', 'j', 'm'] = ['i', 'j', 'm']
           (addP j S2816 S2816)		; j + ['i', 'j', 'l'] = ['i', 'j', 'l']
           (addP j S6400 S6912)		; j + ['i', 'm', 'l'] = ['i', 'j', 'm', 'l']
           (addP j S1664 S1664)		; j + ['h', 'k', 'j'] = ['h', 'k', 'j']
           (addP j S5248 S5760)		; j + ['h', 'k', 'm'] = ['h', 'k', 'j', 'm']
           (addP j S3200 S3712)		; j + ['h', 'k', 'l'] = ['h', 'k', 'j', 'l']
           (addP j S4736 S4736)		; j + ['h', 'j', 'm'] = ['h', 'j', 'm']
           (addP j S2688 S2688)		; j + ['h', 'j', 'l'] = ['h', 'j', 'l']
           (addP j S6272 S6784)		; j + ['h', 'm', 'l'] = ['h', 'j', 'm', 'l']
           (addP j S5632 S5632)		; j + ['k', 'j', 'm'] = ['k', 'j', 'm']
           (addP j S3584 S3584)		; j + ['k', 'j', 'l'] = ['k', 'j', 'l']
           (addP j S7168 S7680)		; j + ['k', 'm', 'l'] = ['k', 'j', 'm', 'l']
           (addP j S6656 S6656)		; j + ['j', 'm', 'l'] = ['j', 'm', 'l']
           (addP j S1409 S1921)		; j + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'j', 'h']
           (addP j S897 S897)		; j + ['a', 'i', 'h', 'j'] = ['a', 'i', 'j', 'h']
           (addP j S4481 S4993)		; j + ['a', 'i', 'h', 'm'] = ['a', 'i', 'j', 'm', 'h']
           (addP j S2433 S2945)		; j + ['a', 'i', 'h', 'l'] = ['a', 'i', 'j', 'l', 'h']
           (addP j S1793 S1793)		; j + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j']
           (addP j S5377 S5889)		; j + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP j S3329 S3841)		; j + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP j S4865 S4865)		; j + ['a', 'i', 'j', 'm'] = ['a', 'i', 'j', 'm']
           (addP j S2817 S2817)		; j + ['a', 'i', 'j', 'l'] = ['a', 'i', 'j', 'l']
           (addP j S6401 S6913)		; j + ['a', 'i', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP j S1665 S1665)		; j + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j']
           (addP j S5249 S5761)		; j + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP j S3201 S3713)		; j + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP j S4737 S4737)		; j + ['a', 'h', 'j', 'm'] = ['a', 'h', 'j', 'm']
           (addP j S2689 S2689)		; j + ['a', 'h', 'j', 'l'] = ['a', 'h', 'j', 'l']
           (addP j S6273 S6785)		; j + ['a', 'h', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP j S5633 S5633)		; j + ['a', 'k', 'j', 'm'] = ['a', 'k', 'j', 'm']
           (addP j S3585 S3585)		; j + ['a', 'k', 'j', 'l'] = ['a', 'k', 'j', 'l']
           (addP j S7169 S7681)		; j + ['a', 'k', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP j S6657 S6657)		; j + ['a', 'j', 'm', 'l'] = ['a', 'j', 'm', 'l']
           (addP j S1920 S1920)		; j + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j']
           (addP j S5504 S6016)		; j + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP j S3456 S3968)		; j + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP j S4992 S4992)		; j + ['i', 'h', 'j', 'm'] = ['i', 'h', 'j', 'm']
           (addP j S2944 S2944)		; j + ['i', 'h', 'j', 'l'] = ['i', 'h', 'j', 'l']
           (addP j S6528 S7040)		; j + ['i', 'h', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP j S5888 S5888)		; j + ['i', 'k', 'j', 'm'] = ['i', 'k', 'j', 'm']
           (addP j S3840 S3840)		; j + ['i', 'k', 'j', 'l'] = ['i', 'k', 'j', 'l']
           (addP j S7424 S7936)		; j + ['i', 'k', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP j S6912 S6912)		; j + ['i', 'j', 'm', 'l'] = ['i', 'j', 'm', 'l']
           (addP j S5760 S5760)		; j + ['h', 'k', 'j', 'm'] = ['h', 'k', 'j', 'm']
           (addP j S3712 S3712)		; j + ['h', 'k', 'j', 'l'] = ['h', 'k', 'j', 'l']
           (addP j S7296 S7808)		; j + ['h', 'k', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP j S6784 S6784)		; j + ['h', 'j', 'm', 'l'] = ['h', 'j', 'm', 'l']
           (addP j S7680 S7680)		; j + ['k', 'j', 'm', 'l'] = ['k', 'j', 'm', 'l']
           (addP j S1921 S1921)		; j + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j']
           (addP j S5505 S6017)		; j + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP j S3457 S3969)		; j + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP j S4993 S4993)		; j + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'j', 'm']
           (addP j S2945 S2945)		; j + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'j', 'l']
           (addP j S6529 S7041)		; j + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP j S5889 S5889)		; j + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP j S3841 S3841)		; j + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP j S7425 S7937)		; j + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP j S6913 S6913)		; j + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP j S5761 S5761)		; j + ['a', 'h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP j S3713 S3713)		; j + ['a', 'h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP j S7297 S7809)		; j + ['a', 'h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP j S6785 S6785)		; j + ['a', 'h', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP j S7681 S7681)		; j + ['a', 'k', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP j S6016 S6016)		; j + ['i', 'h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP j S3968 S3968)		; j + ['i', 'h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP j S7552 S8064)		; j + ['i', 'h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP j S7040 S7040)		; j + ['i', 'h', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP j S7936 S7936)		; j + ['i', 'k', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP j S7808 S7808)		; j + ['h', 'k', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP j S6017 S6017)		; j + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP j S3969 S3969)		; j + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP j S7553 S8065)		; j + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP j S7041 S7041)		; j + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP j S7937 S7937)		; j + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP j S7809 S7809)		; j + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP j S8064 S8064)		; j + ['i', 'h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP j S8065 S8065)		; j + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP m S0 S4096)		; m + [] = ['m']
           (addP m S1 S4097)		; m + ['a'] = ['a', 'm']
           (addP m S256 S4352)		; m + ['i'] = ['i', 'm']
           (addP m S128 S4224)		; m + ['h'] = ['h', 'm']
           (addP m S1024 S5120)		; m + ['k'] = ['k', 'm']
           (addP m S512 S4608)		; m + ['j'] = ['j', 'm']
           (addP m S4096 S4096)		; m + ['m'] = ['m']
           (addP m S2048 S6144)		; m + ['l'] = ['m', 'l']
           (addP m S257 S4353)		; m + ['a', 'i'] = ['a', 'i', 'm']
           (addP m S129 S4225)		; m + ['a', 'h'] = ['a', 'h', 'm']
           (addP m S1025 S5121)		; m + ['a', 'k'] = ['a', 'k', 'm']
           (addP m S513 S4609)		; m + ['a', 'j'] = ['a', 'j', 'm']
           (addP m S4097 S4097)		; m + ['a', 'm'] = ['a', 'm']
           (addP m S2049 S6145)		; m + ['a', 'l'] = ['a', 'm', 'l']
           (addP m S384 S4480)		; m + ['i', 'h'] = ['i', 'h', 'm']
           (addP m S1280 S5376)		; m + ['i', 'k'] = ['i', 'k', 'm']
           (addP m S768 S4864)		; m + ['i', 'j'] = ['i', 'j', 'm']
           (addP m S4352 S4352)		; m + ['i', 'm'] = ['i', 'm']
           (addP m S2304 S6400)		; m + ['i', 'l'] = ['i', 'm', 'l']
           (addP m S1152 S5248)		; m + ['h', 'k'] = ['h', 'k', 'm']
           (addP m S640 S4736)		; m + ['h', 'j'] = ['h', 'j', 'm']
           (addP m S4224 S4224)		; m + ['h', 'm'] = ['h', 'm']
           (addP m S2176 S6272)		; m + ['h', 'l'] = ['h', 'm', 'l']
           (addP m S1536 S5632)		; m + ['k', 'j'] = ['k', 'j', 'm']
           (addP m S5120 S5120)		; m + ['k', 'm'] = ['k', 'm']
           (addP m S3072 S7168)		; m + ['k', 'l'] = ['k', 'm', 'l']
           (addP m S4608 S4608)		; m + ['j', 'm'] = ['j', 'm']
           (addP m S2560 S6656)		; m + ['j', 'l'] = ['j', 'm', 'l']
           (addP m S6144 S6144)		; m + ['m', 'l'] = ['m', 'l']
           (addP m S385 S4481)		; m + ['a', 'i', 'h'] = ['a', 'i', 'm', 'h']
           (addP m S1281 S5377)		; m + ['a', 'i', 'k'] = ['a', 'i', 'k', 'm']
           (addP m S769 S4865)		; m + ['a', 'i', 'j'] = ['a', 'i', 'j', 'm']
           (addP m S4353 S4353)		; m + ['a', 'i', 'm'] = ['a', 'i', 'm']
           (addP m S2305 S6401)		; m + ['a', 'i', 'l'] = ['a', 'i', 'm', 'l']
           (addP m S1153 S5249)		; m + ['a', 'h', 'k'] = ['a', 'h', 'k', 'm']
           (addP m S641 S4737)		; m + ['a', 'h', 'j'] = ['a', 'h', 'j', 'm']
           (addP m S4225 S4225)		; m + ['a', 'h', 'm'] = ['a', 'h', 'm']
           (addP m S2177 S6273)		; m + ['a', 'h', 'l'] = ['a', 'h', 'm', 'l']
           (addP m S1537 S5633)		; m + ['a', 'k', 'j'] = ['a', 'k', 'j', 'm']
           (addP m S5121 S5121)		; m + ['a', 'k', 'm'] = ['a', 'k', 'm']
           (addP m S3073 S7169)		; m + ['a', 'k', 'l'] = ['a', 'k', 'm', 'l']
           (addP m S4609 S4609)		; m + ['a', 'j', 'm'] = ['a', 'j', 'm']
           (addP m S2561 S6657)		; m + ['a', 'j', 'l'] = ['a', 'j', 'm', 'l']
           (addP m S6145 S6145)		; m + ['a', 'm', 'l'] = ['a', 'm', 'l']
           (addP m S1408 S5504)		; m + ['i', 'h', 'k'] = ['i', 'h', 'k', 'm']
           (addP m S896 S4992)		; m + ['i', 'h', 'j'] = ['i', 'h', 'j', 'm']
           (addP m S4480 S4480)		; m + ['i', 'h', 'm'] = ['i', 'h', 'm']
           (addP m S2432 S6528)		; m + ['i', 'h', 'l'] = ['i', 'h', 'm', 'l']
           (addP m S1792 S5888)		; m + ['i', 'k', 'j'] = ['i', 'k', 'j', 'm']
           (addP m S5376 S5376)		; m + ['i', 'k', 'm'] = ['i', 'k', 'm']
           (addP m S3328 S7424)		; m + ['i', 'k', 'l'] = ['i', 'k', 'm', 'l']
           (addP m S4864 S4864)		; m + ['i', 'j', 'm'] = ['i', 'j', 'm']
           (addP m S2816 S6912)		; m + ['i', 'j', 'l'] = ['i', 'j', 'm', 'l']
           (addP m S6400 S6400)		; m + ['i', 'm', 'l'] = ['i', 'm', 'l']
           (addP m S1664 S5760)		; m + ['h', 'k', 'j'] = ['h', 'k', 'j', 'm']
           (addP m S5248 S5248)		; m + ['h', 'k', 'm'] = ['h', 'k', 'm']
           (addP m S3200 S7296)		; m + ['h', 'k', 'l'] = ['h', 'k', 'm', 'l']
           (addP m S4736 S4736)		; m + ['h', 'j', 'm'] = ['h', 'j', 'm']
           (addP m S2688 S6784)		; m + ['h', 'j', 'l'] = ['h', 'j', 'm', 'l']
           (addP m S6272 S6272)		; m + ['h', 'm', 'l'] = ['h', 'm', 'l']
           (addP m S5632 S5632)		; m + ['k', 'j', 'm'] = ['k', 'j', 'm']
           (addP m S3584 S7680)		; m + ['k', 'j', 'l'] = ['k', 'j', 'm', 'l']
           (addP m S7168 S7168)		; m + ['k', 'm', 'l'] = ['k', 'm', 'l']
           (addP m S6656 S6656)		; m + ['j', 'm', 'l'] = ['j', 'm', 'l']
           (addP m S1409 S5505)		; m + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'm', 'h']
           (addP m S897 S4993)		; m + ['a', 'i', 'h', 'j'] = ['a', 'i', 'j', 'm', 'h']
           (addP m S4481 S4481)		; m + ['a', 'i', 'h', 'm'] = ['a', 'i', 'm', 'h']
           (addP m S2433 S6529)		; m + ['a', 'i', 'h', 'l'] = ['a', 'i', 'm', 'l', 'h']
           (addP m S1793 S5889)		; m + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j', 'm']
           (addP m S5377 S5377)		; m + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'm']
           (addP m S3329 S7425)		; m + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP m S4865 S4865)		; m + ['a', 'i', 'j', 'm'] = ['a', 'i', 'j', 'm']
           (addP m S2817 S6913)		; m + ['a', 'i', 'j', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP m S6401 S6401)		; m + ['a', 'i', 'm', 'l'] = ['a', 'i', 'm', 'l']
           (addP m S1665 S5761)		; m + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j', 'm']
           (addP m S5249 S5249)		; m + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'm']
           (addP m S3201 S7297)		; m + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP m S4737 S4737)		; m + ['a', 'h', 'j', 'm'] = ['a', 'h', 'j', 'm']
           (addP m S2689 S6785)		; m + ['a', 'h', 'j', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP m S6273 S6273)		; m + ['a', 'h', 'm', 'l'] = ['a', 'h', 'm', 'l']
           (addP m S5633 S5633)		; m + ['a', 'k', 'j', 'm'] = ['a', 'k', 'j', 'm']
           (addP m S3585 S7681)		; m + ['a', 'k', 'j', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP m S7169 S7169)		; m + ['a', 'k', 'm', 'l'] = ['a', 'k', 'm', 'l']
           (addP m S6657 S6657)		; m + ['a', 'j', 'm', 'l'] = ['a', 'j', 'm', 'l']
           (addP m S1920 S6016)		; m + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j', 'm']
           (addP m S5504 S5504)		; m + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'm']
           (addP m S3456 S7552)		; m + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP m S4992 S4992)		; m + ['i', 'h', 'j', 'm'] = ['i', 'h', 'j', 'm']
           (addP m S2944 S7040)		; m + ['i', 'h', 'j', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP m S6528 S6528)		; m + ['i', 'h', 'm', 'l'] = ['i', 'h', 'm', 'l']
           (addP m S5888 S5888)		; m + ['i', 'k', 'j', 'm'] = ['i', 'k', 'j', 'm']
           (addP m S3840 S7936)		; m + ['i', 'k', 'j', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP m S7424 S7424)		; m + ['i', 'k', 'm', 'l'] = ['i', 'k', 'm', 'l']
           (addP m S6912 S6912)		; m + ['i', 'j', 'm', 'l'] = ['i', 'j', 'm', 'l']
           (addP m S5760 S5760)		; m + ['h', 'k', 'j', 'm'] = ['h', 'k', 'j', 'm']
           (addP m S3712 S7808)		; m + ['h', 'k', 'j', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP m S7296 S7296)		; m + ['h', 'k', 'm', 'l'] = ['h', 'k', 'm', 'l']
           (addP m S6784 S6784)		; m + ['h', 'j', 'm', 'l'] = ['h', 'j', 'm', 'l']
           (addP m S7680 S7680)		; m + ['k', 'j', 'm', 'l'] = ['k', 'j', 'm', 'l']
           (addP m S1921 S6017)		; m + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP m S5505 S5505)		; m + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'm']
           (addP m S3457 S7553)		; m + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP m S4993 S4993)		; m + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'j', 'm']
           (addP m S2945 S7041)		; m + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP m S6529 S6529)		; m + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'm', 'l']
           (addP m S5889 S5889)		; m + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm']
           (addP m S3841 S7937)		; m + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP m S7425 S7425)		; m + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP m S6913 S6913)		; m + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP m S5761 S5761)		; m + ['a', 'h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm']
           (addP m S3713 S7809)		; m + ['a', 'h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP m S7297 S7297)		; m + ['a', 'h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP m S6785 S6785)		; m + ['a', 'h', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP m S7681 S7681)		; m + ['a', 'k', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP m S6016 S6016)		; m + ['i', 'h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm']
           (addP m S3968 S8064)		; m + ['i', 'h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP m S7552 S7552)		; m + ['i', 'h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP m S7040 S7040)		; m + ['i', 'h', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP m S7936 S7936)		; m + ['i', 'k', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP m S7808 S7808)		; m + ['h', 'k', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP m S6017 S6017)		; m + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm']
           (addP m S3969 S8065)		; m + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP m S7553 S7553)		; m + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP m S7041 S7041)		; m + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP m S7937 S7937)		; m + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP m S7809 S7809)		; m + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP m S8064 S8064)		; m + ['i', 'h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP m S8065 S8065)		; m + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP l S0 S2048)		; l + [] = ['l']
           (addP l S1 S2049)		; l + ['a'] = ['a', 'l']
           (addP l S256 S2304)		; l + ['i'] = ['i', 'l']
           (addP l S128 S2176)		; l + ['h'] = ['h', 'l']
           (addP l S1024 S3072)		; l + ['k'] = ['k', 'l']
           (addP l S512 S2560)		; l + ['j'] = ['j', 'l']
           (addP l S4096 S6144)		; l + ['m'] = ['m', 'l']
           (addP l S2048 S2048)		; l + ['l'] = ['l']
           (addP l S257 S2305)		; l + ['a', 'i'] = ['a', 'i', 'l']
           (addP l S129 S2177)		; l + ['a', 'h'] = ['a', 'h', 'l']
           (addP l S1025 S3073)		; l + ['a', 'k'] = ['a', 'k', 'l']
           (addP l S513 S2561)		; l + ['a', 'j'] = ['a', 'j', 'l']
           (addP l S4097 S6145)		; l + ['a', 'm'] = ['a', 'm', 'l']
           (addP l S2049 S2049)		; l + ['a', 'l'] = ['a', 'l']
           (addP l S384 S2432)		; l + ['i', 'h'] = ['i', 'h', 'l']
           (addP l S1280 S3328)		; l + ['i', 'k'] = ['i', 'k', 'l']
           (addP l S768 S2816)		; l + ['i', 'j'] = ['i', 'j', 'l']
           (addP l S4352 S6400)		; l + ['i', 'm'] = ['i', 'm', 'l']
           (addP l S2304 S2304)		; l + ['i', 'l'] = ['i', 'l']
           (addP l S1152 S3200)		; l + ['h', 'k'] = ['h', 'k', 'l']
           (addP l S640 S2688)		; l + ['h', 'j'] = ['h', 'j', 'l']
           (addP l S4224 S6272)		; l + ['h', 'm'] = ['h', 'm', 'l']
           (addP l S2176 S2176)		; l + ['h', 'l'] = ['h', 'l']
           (addP l S1536 S3584)		; l + ['k', 'j'] = ['k', 'j', 'l']
           (addP l S5120 S7168)		; l + ['k', 'm'] = ['k', 'm', 'l']
           (addP l S3072 S3072)		; l + ['k', 'l'] = ['k', 'l']
           (addP l S4608 S6656)		; l + ['j', 'm'] = ['j', 'm', 'l']
           (addP l S2560 S2560)		; l + ['j', 'l'] = ['j', 'l']
           (addP l S6144 S6144)		; l + ['m', 'l'] = ['m', 'l']
           (addP l S385 S2433)		; l + ['a', 'i', 'h'] = ['a', 'i', 'l', 'h']
           (addP l S1281 S3329)		; l + ['a', 'i', 'k'] = ['a', 'i', 'k', 'l']
           (addP l S769 S2817)		; l + ['a', 'i', 'j'] = ['a', 'i', 'j', 'l']
           (addP l S4353 S6401)		; l + ['a', 'i', 'm'] = ['a', 'i', 'm', 'l']
           (addP l S2305 S2305)		; l + ['a', 'i', 'l'] = ['a', 'i', 'l']
           (addP l S1153 S3201)		; l + ['a', 'h', 'k'] = ['a', 'h', 'k', 'l']
           (addP l S641 S2689)		; l + ['a', 'h', 'j'] = ['a', 'h', 'j', 'l']
           (addP l S4225 S6273)		; l + ['a', 'h', 'm'] = ['a', 'h', 'm', 'l']
           (addP l S2177 S2177)		; l + ['a', 'h', 'l'] = ['a', 'h', 'l']
           (addP l S1537 S3585)		; l + ['a', 'k', 'j'] = ['a', 'k', 'j', 'l']
           (addP l S5121 S7169)		; l + ['a', 'k', 'm'] = ['a', 'k', 'm', 'l']
           (addP l S3073 S3073)		; l + ['a', 'k', 'l'] = ['a', 'k', 'l']
           (addP l S4609 S6657)		; l + ['a', 'j', 'm'] = ['a', 'j', 'm', 'l']
           (addP l S2561 S2561)		; l + ['a', 'j', 'l'] = ['a', 'j', 'l']
           (addP l S6145 S6145)		; l + ['a', 'm', 'l'] = ['a', 'm', 'l']
           (addP l S1408 S3456)		; l + ['i', 'h', 'k'] = ['i', 'h', 'k', 'l']
           (addP l S896 S2944)		; l + ['i', 'h', 'j'] = ['i', 'h', 'j', 'l']
           (addP l S4480 S6528)		; l + ['i', 'h', 'm'] = ['i', 'h', 'm', 'l']
           (addP l S2432 S2432)		; l + ['i', 'h', 'l'] = ['i', 'h', 'l']
           (addP l S1792 S3840)		; l + ['i', 'k', 'j'] = ['i', 'k', 'j', 'l']
           (addP l S5376 S7424)		; l + ['i', 'k', 'm'] = ['i', 'k', 'm', 'l']
           (addP l S3328 S3328)		; l + ['i', 'k', 'l'] = ['i', 'k', 'l']
           (addP l S4864 S6912)		; l + ['i', 'j', 'm'] = ['i', 'j', 'm', 'l']
           (addP l S2816 S2816)		; l + ['i', 'j', 'l'] = ['i', 'j', 'l']
           (addP l S6400 S6400)		; l + ['i', 'm', 'l'] = ['i', 'm', 'l']
           (addP l S1664 S3712)		; l + ['h', 'k', 'j'] = ['h', 'k', 'j', 'l']
           (addP l S5248 S7296)		; l + ['h', 'k', 'm'] = ['h', 'k', 'm', 'l']
           (addP l S3200 S3200)		; l + ['h', 'k', 'l'] = ['h', 'k', 'l']
           (addP l S4736 S6784)		; l + ['h', 'j', 'm'] = ['h', 'j', 'm', 'l']
           (addP l S2688 S2688)		; l + ['h', 'j', 'l'] = ['h', 'j', 'l']
           (addP l S6272 S6272)		; l + ['h', 'm', 'l'] = ['h', 'm', 'l']
           (addP l S5632 S7680)		; l + ['k', 'j', 'm'] = ['k', 'j', 'm', 'l']
           (addP l S3584 S3584)		; l + ['k', 'j', 'l'] = ['k', 'j', 'l']
           (addP l S7168 S7168)		; l + ['k', 'm', 'l'] = ['k', 'm', 'l']
           (addP l S6656 S6656)		; l + ['j', 'm', 'l'] = ['j', 'm', 'l']
           (addP l S1409 S3457)		; l + ['a', 'i', 'h', 'k'] = ['a', 'i', 'k', 'l', 'h']
           (addP l S897 S2945)		; l + ['a', 'i', 'h', 'j'] = ['a', 'i', 'j', 'l', 'h']
           (addP l S4481 S6529)		; l + ['a', 'i', 'h', 'm'] = ['a', 'i', 'm', 'l', 'h']
           (addP l S2433 S2433)		; l + ['a', 'i', 'h', 'l'] = ['a', 'i', 'l', 'h']
           (addP l S1793 S3841)		; l + ['a', 'i', 'k', 'j'] = ['a', 'i', 'k', 'j', 'l']
           (addP l S5377 S7425)		; l + ['a', 'i', 'k', 'm'] = ['a', 'i', 'k', 'm', 'l']
           (addP l S3329 S3329)		; l + ['a', 'i', 'k', 'l'] = ['a', 'i', 'k', 'l']
           (addP l S4865 S6913)		; l + ['a', 'i', 'j', 'm'] = ['a', 'i', 'j', 'm', 'l']
           (addP l S2817 S2817)		; l + ['a', 'i', 'j', 'l'] = ['a', 'i', 'j', 'l']
           (addP l S6401 S6401)		; l + ['a', 'i', 'm', 'l'] = ['a', 'i', 'm', 'l']
           (addP l S1665 S3713)		; l + ['a', 'h', 'k', 'j'] = ['a', 'h', 'k', 'j', 'l']
           (addP l S5249 S7297)		; l + ['a', 'h', 'k', 'm'] = ['a', 'h', 'k', 'm', 'l']
           (addP l S3201 S3201)		; l + ['a', 'h', 'k', 'l'] = ['a', 'h', 'k', 'l']
           (addP l S4737 S6785)		; l + ['a', 'h', 'j', 'm'] = ['a', 'h', 'j', 'm', 'l']
           (addP l S2689 S2689)		; l + ['a', 'h', 'j', 'l'] = ['a', 'h', 'j', 'l']
           (addP l S6273 S6273)		; l + ['a', 'h', 'm', 'l'] = ['a', 'h', 'm', 'l']
           (addP l S5633 S7681)		; l + ['a', 'k', 'j', 'm'] = ['a', 'k', 'j', 'm', 'l']
           (addP l S3585 S3585)		; l + ['a', 'k', 'j', 'l'] = ['a', 'k', 'j', 'l']
           (addP l S7169 S7169)		; l + ['a', 'k', 'm', 'l'] = ['a', 'k', 'm', 'l']
           (addP l S6657 S6657)		; l + ['a', 'j', 'm', 'l'] = ['a', 'j', 'm', 'l']
           (addP l S1920 S3968)		; l + ['i', 'h', 'k', 'j'] = ['i', 'h', 'k', 'j', 'l']
           (addP l S5504 S7552)		; l + ['i', 'h', 'k', 'm'] = ['i', 'h', 'k', 'm', 'l']
           (addP l S3456 S3456)		; l + ['i', 'h', 'k', 'l'] = ['i', 'h', 'k', 'l']
           (addP l S4992 S7040)		; l + ['i', 'h', 'j', 'm'] = ['i', 'h', 'j', 'm', 'l']
           (addP l S2944 S2944)		; l + ['i', 'h', 'j', 'l'] = ['i', 'h', 'j', 'l']
           (addP l S6528 S6528)		; l + ['i', 'h', 'm', 'l'] = ['i', 'h', 'm', 'l']
           (addP l S5888 S7936)		; l + ['i', 'k', 'j', 'm'] = ['i', 'k', 'j', 'm', 'l']
           (addP l S3840 S3840)		; l + ['i', 'k', 'j', 'l'] = ['i', 'k', 'j', 'l']
           (addP l S7424 S7424)		; l + ['i', 'k', 'm', 'l'] = ['i', 'k', 'm', 'l']
           (addP l S6912 S6912)		; l + ['i', 'j', 'm', 'l'] = ['i', 'j', 'm', 'l']
           (addP l S5760 S7808)		; l + ['h', 'k', 'j', 'm'] = ['h', 'k', 'j', 'm', 'l']
           (addP l S3712 S3712)		; l + ['h', 'k', 'j', 'l'] = ['h', 'k', 'j', 'l']
           (addP l S7296 S7296)		; l + ['h', 'k', 'm', 'l'] = ['h', 'k', 'm', 'l']
           (addP l S6784 S6784)		; l + ['h', 'j', 'm', 'l'] = ['h', 'j', 'm', 'l']
           (addP l S7680 S7680)		; l + ['k', 'j', 'm', 'l'] = ['k', 'j', 'm', 'l']
           (addP l S1921 S3969)		; l + ['a', 'i', 'h', 'k', 'j'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP l S5505 S7553)		; l + ['a', 'i', 'h', 'k', 'm'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP l S3457 S3457)		; l + ['a', 'i', 'h', 'k', 'l'] = ['a', 'i', 'h', 'k', 'l']
           (addP l S4993 S7041)		; l + ['a', 'i', 'h', 'j', 'm'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP l S2945 S2945)		; l + ['a', 'i', 'h', 'j', 'l'] = ['a', 'i', 'h', 'j', 'l']
           (addP l S6529 S6529)		; l + ['a', 'i', 'h', 'm', 'l'] = ['a', 'i', 'h', 'm', 'l']
           (addP l S5889 S7937)		; l + ['a', 'i', 'k', 'j', 'm'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP l S3841 S3841)		; l + ['a', 'i', 'k', 'j', 'l'] = ['a', 'i', 'k', 'j', 'l']
           (addP l S7425 S7425)		; l + ['a', 'i', 'k', 'm', 'l'] = ['a', 'i', 'k', 'm', 'l']
           (addP l S6913 S6913)		; l + ['a', 'i', 'j', 'm', 'l'] = ['a', 'i', 'j', 'm', 'l']
           (addP l S5761 S7809)		; l + ['a', 'h', 'k', 'j', 'm'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP l S3713 S3713)		; l + ['a', 'h', 'k', 'j', 'l'] = ['a', 'h', 'k', 'j', 'l']
           (addP l S7297 S7297)		; l + ['a', 'h', 'k', 'm', 'l'] = ['a', 'h', 'k', 'm', 'l']
           (addP l S6785 S6785)		; l + ['a', 'h', 'j', 'm', 'l'] = ['a', 'h', 'j', 'm', 'l']
           (addP l S7681 S7681)		; l + ['a', 'k', 'j', 'm', 'l'] = ['a', 'k', 'j', 'm', 'l']
           (addP l S6016 S8064)		; l + ['i', 'h', 'k', 'j', 'm'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP l S3968 S3968)		; l + ['i', 'h', 'k', 'j', 'l'] = ['i', 'h', 'k', 'j', 'l']
           (addP l S7552 S7552)		; l + ['i', 'h', 'k', 'm', 'l'] = ['i', 'h', 'k', 'm', 'l']
           (addP l S7040 S7040)		; l + ['i', 'h', 'j', 'm', 'l'] = ['i', 'h', 'j', 'm', 'l']
           (addP l S7936 S7936)		; l + ['i', 'k', 'j', 'm', 'l'] = ['i', 'k', 'j', 'm', 'l']
           (addP l S7808 S7808)		; l + ['h', 'k', 'j', 'm', 'l'] = ['h', 'k', 'j', 'm', 'l']
           (addP l S6017 S8065)		; l + ['a', 'i', 'h', 'k', 'j', 'm'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']
           (addP l S3969 S3969)		; l + ['a', 'i', 'h', 'k', 'j', 'l'] = ['a', 'i', 'h', 'k', 'j', 'l']
           (addP l S7553 S7553)		; l + ['a', 'i', 'h', 'k', 'm', 'l'] = ['a', 'i', 'h', 'k', 'm', 'l']
           (addP l S7041 S7041)		; l + ['a', 'i', 'h', 'j', 'm', 'l'] = ['a', 'i', 'h', 'j', 'm', 'l']
           (addP l S7937 S7937)		; l + ['a', 'i', 'k', 'j', 'm', 'l'] = ['a', 'i', 'k', 'j', 'm', 'l']
           (addP l S7809 S7809)		; l + ['a', 'h', 'k', 'j', 'm', 'l'] = ['a', 'h', 'k', 'j', 'm', 'l']
           (addP l S8064 S8064)		; l + ['i', 'h', 'k', 'j', 'm', 'l'] = ['i', 'h', 'k', 'j', 'm', 'l']
           (addP l S8065 S8065)		; l + ['a', 'i', 'h', 'k', 'j', 'm', 'l'] = ['a', 'i', 'h', 'k', 'j', 'm', 'l']

           (addO T0 T0 T0)		; [] + [] = []
           (addO T0 T2 T2)		; [] + ['b'] = ['b']
           (addO T0 T16 T16)		; [] + ['e'] = ['e']
           (addO T0 T18 T18)		; [] + ['b', 'e'] = ['b', 'e']
           (addO T2 T0 T2)		; ['b'] + [] = ['b']
           (addO T2 T2 T2)		; ['b'] + ['b'] = ['b']
           (addO T2 T16 T18)		; ['b'] + ['e'] = ['b', 'e']
           (addO T2 T18 T18)		; ['b'] + ['b', 'e'] = ['b', 'e']
           (addO T16 T0 T16)		; ['e'] + [] = ['e']
           (addO T16 T2 T18)		; ['e'] + ['b'] = ['b', 'e']
           (addO T16 T16 T16)		; ['e'] + ['e'] = ['e']
           (addO T16 T18 T18)		; ['e'] + ['b', 'e'] = ['b', 'e']
           (addO T18 T0 T18)		; ['b', 'e'] + [] = ['b', 'e']
           (addO T18 T2 T18)		; ['b', 'e'] + ['b'] = ['b', 'e']
           (addO T18 T16 T18)		; ['b', 'e'] + ['e'] = ['b', 'e']
           (addO T18 T18 T18)		; ['b', 'e'] + ['b', 'e'] = ['b', 'e']

           (canAssertO T0 A1 S0)		; A1: [] -> []
           (canAssertO T0 A1 S1)		; A1: ['a'] -> []
           (canAssertO T0 A1 S256)		; A1: ['i'] -> []
           (canAssertO T0 A1 S128)		; A1: ['h'] -> []
           (canAssertO T0 A1 S1024)		; A1: ['k'] -> []
           (canAssertO T0 A1 S512)		; A1: ['j'] -> []
           (canAssertO T0 A1 S4096)		; A1: ['m'] -> []
           (canAssertO T0 A1 S2048)		; A1: ['l'] -> []
           (canAssertO T0 A1 S257)		; A1: ['a', 'i'] -> []
           (canAssertO T0 A1 S129)		; A1: ['a', 'h'] -> []
           (canAssertO T0 A1 S1025)		; A1: ['a', 'k'] -> []
           (canAssertO T0 A1 S513)		; A1: ['a', 'j'] -> []
           (canAssertO T0 A1 S4097)		; A1: ['a', 'm'] -> []
           (canAssertO T0 A1 S2049)		; A1: ['a', 'l'] -> []
           (canAssertO T0 A1 S384)		; A1: ['i', 'h'] -> []
           (canAssertO T0 A1 S1280)		; A1: ['i', 'k'] -> []
           (canAssertO T0 A1 S768)		; A1: ['i', 'j'] -> []
           (canAssertO T0 A1 S4352)		; A1: ['i', 'm'] -> []
           (canAssertO T0 A1 S2304)		; A1: ['i', 'l'] -> []
           (canAssertO T0 A1 S1152)		; A1: ['h', 'k'] -> []
           (canAssertO T0 A1 S640)		; A1: ['h', 'j'] -> []
           (canAssertO T0 A1 S4224)		; A1: ['h', 'm'] -> []
           (canAssertO T0 A1 S2176)		; A1: ['h', 'l'] -> []
           (canAssertO T0 A1 S1536)		; A1: ['k', 'j'] -> []
           (canAssertO T0 A1 S5120)		; A1: ['k', 'm'] -> []
           (canAssertO T0 A1 S3072)		; A1: ['k', 'l'] -> []
           (canAssertO T0 A1 S4608)		; A1: ['j', 'm'] -> []
           (canAssertO T0 A1 S2560)		; A1: ['j', 'l'] -> []
           (canAssertO T0 A1 S6144)		; A1: ['m', 'l'] -> []
           (canAssertO T0 A1 S385)		; A1: ['a', 'i', 'h'] -> []
           (canAssertO T0 A1 S1281)		; A1: ['a', 'i', 'k'] -> []
           (canAssertO T0 A1 S769)		; A1: ['a', 'i', 'j'] -> []
           (canAssertO T0 A1 S4353)		; A1: ['a', 'i', 'm'] -> []
           (canAssertO T0 A1 S2305)		; A1: ['a', 'i', 'l'] -> []
           (canAssertO T0 A1 S1153)		; A1: ['a', 'h', 'k'] -> []
           (canAssertO T0 A1 S641)		; A1: ['a', 'h', 'j'] -> []
           (canAssertO T0 A1 S4225)		; A1: ['a', 'h', 'm'] -> []
           (canAssertO T0 A1 S2177)		; A1: ['a', 'h', 'l'] -> []
           (canAssertO T0 A1 S1537)		; A1: ['a', 'k', 'j'] -> []
           (canAssertO T0 A1 S5121)		; A1: ['a', 'k', 'm'] -> []
           (canAssertO T0 A1 S3073)		; A1: ['a', 'k', 'l'] -> []
           (canAssertO T0 A1 S4609)		; A1: ['a', 'j', 'm'] -> []
           (canAssertO T0 A1 S2561)		; A1: ['a', 'j', 'l'] -> []
           (canAssertO T0 A1 S6145)		; A1: ['a', 'm', 'l'] -> []
           (canAssertO T0 A1 S1408)		; A1: ['i', 'h', 'k'] -> []
           (canAssertO T0 A1 S896)		; A1: ['i', 'h', 'j'] -> []
           (canAssertO T0 A1 S4480)		; A1: ['i', 'h', 'm'] -> []
           (canAssertO T0 A1 S2432)		; A1: ['i', 'h', 'l'] -> []
           (canAssertO T0 A1 S1792)		; A1: ['i', 'k', 'j'] -> []
           (canAssertO T0 A1 S5376)		; A1: ['i', 'k', 'm'] -> []
           (canAssertO T0 A1 S3328)		; A1: ['i', 'k', 'l'] -> []
           (canAssertO T0 A1 S4864)		; A1: ['i', 'j', 'm'] -> []
           (canAssertO T0 A1 S2816)		; A1: ['i', 'j', 'l'] -> []
           (canAssertO T0 A1 S6400)		; A1: ['i', 'm', 'l'] -> []
           (canAssertO T0 A1 S1664)		; A1: ['h', 'k', 'j'] -> []
           (canAssertO T0 A1 S5248)		; A1: ['h', 'k', 'm'] -> []
           (canAssertO T0 A1 S3200)		; A1: ['h', 'k', 'l'] -> []
           (canAssertO T0 A1 S4736)		; A1: ['h', 'j', 'm'] -> []
           (canAssertO T0 A1 S2688)		; A1: ['h', 'j', 'l'] -> []
           (canAssertO T0 A1 S6272)		; A1: ['h', 'm', 'l'] -> []
           (canAssertO T0 A1 S5632)		; A1: ['k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3584)		; A1: ['k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7168)		; A1: ['k', 'm', 'l'] -> []
           (canAssertO T0 A1 S6656)		; A1: ['j', 'm', 'l'] -> []
           (canAssertO T0 A1 S1409)		; A1: ['a', 'i', 'h', 'k'] -> []
           (canAssertO T0 A1 S897)		; A1: ['a', 'i', 'h', 'j'] -> []
           (canAssertO T0 A1 S4481)		; A1: ['a', 'i', 'h', 'm'] -> []
           (canAssertO T0 A1 S2433)		; A1: ['a', 'i', 'h', 'l'] -> []
           (canAssertO T0 A1 S1793)		; A1: ['a', 'i', 'k', 'j'] -> []
           (canAssertO T0 A1 S5377)		; A1: ['a', 'i', 'k', 'm'] -> []
           (canAssertO T0 A1 S3329)		; A1: ['a', 'i', 'k', 'l'] -> []
           (canAssertO T0 A1 S4865)		; A1: ['a', 'i', 'j', 'm'] -> []
           (canAssertO T0 A1 S2817)		; A1: ['a', 'i', 'j', 'l'] -> []
           (canAssertO T0 A1 S6401)		; A1: ['a', 'i', 'm', 'l'] -> []
           (canAssertO T0 A1 S1665)		; A1: ['a', 'h', 'k', 'j'] -> []
           (canAssertO T0 A1 S5249)		; A1: ['a', 'h', 'k', 'm'] -> []
           (canAssertO T0 A1 S3201)		; A1: ['a', 'h', 'k', 'l'] -> []
           (canAssertO T0 A1 S4737)		; A1: ['a', 'h', 'j', 'm'] -> []
           (canAssertO T0 A1 S2689)		; A1: ['a', 'h', 'j', 'l'] -> []
           (canAssertO T0 A1 S6273)		; A1: ['a', 'h', 'm', 'l'] -> []
           (canAssertO T0 A1 S5633)		; A1: ['a', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3585)		; A1: ['a', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7169)		; A1: ['a', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S6657)		; A1: ['a', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S1920)		; A1: ['i', 'h', 'k', 'j'] -> []
           (canAssertO T0 A1 S5504)		; A1: ['i', 'h', 'k', 'm'] -> []
           (canAssertO T0 A1 S3456)		; A1: ['i', 'h', 'k', 'l'] -> []
           (canAssertO T0 A1 S4992)		; A1: ['i', 'h', 'j', 'm'] -> []
           (canAssertO T0 A1 S2944)		; A1: ['i', 'h', 'j', 'l'] -> []
           (canAssertO T0 A1 S6528)		; A1: ['i', 'h', 'm', 'l'] -> []
           (canAssertO T0 A1 S5888)		; A1: ['i', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3840)		; A1: ['i', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7424)		; A1: ['i', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S6912)		; A1: ['i', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S5760)		; A1: ['h', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3712)		; A1: ['h', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7296)		; A1: ['h', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S6784)		; A1: ['h', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S7680)		; A1: ['k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S1921)		; A1: ['a', 'i', 'h', 'k', 'j'] -> []
           (canAssertO T0 A1 S5505)		; A1: ['a', 'i', 'h', 'k', 'm'] -> []
           (canAssertO T0 A1 S3457)		; A1: ['a', 'i', 'h', 'k', 'l'] -> []
           (canAssertO T0 A1 S4993)		; A1: ['a', 'i', 'h', 'j', 'm'] -> []
           (canAssertO T0 A1 S2945)		; A1: ['a', 'i', 'h', 'j', 'l'] -> []
           (canAssertO T0 A1 S6529)		; A1: ['a', 'i', 'h', 'm', 'l'] -> []
           (canAssertO T0 A1 S5889)		; A1: ['a', 'i', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3841)		; A1: ['a', 'i', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7425)		; A1: ['a', 'i', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S6913)		; A1: ['a', 'i', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S5761)		; A1: ['a', 'h', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3713)		; A1: ['a', 'h', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7297)		; A1: ['a', 'h', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S6785)		; A1: ['a', 'h', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S7681)		; A1: ['a', 'k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S6016)		; A1: ['i', 'h', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3968)		; A1: ['i', 'h', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7552)		; A1: ['i', 'h', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S7040)		; A1: ['i', 'h', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S7936)		; A1: ['i', 'k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S7808)		; A1: ['h', 'k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S6017)		; A1: ['a', 'i', 'h', 'k', 'j', 'm'] -> []
           (canAssertO T0 A1 S3969)		; A1: ['a', 'i', 'h', 'k', 'j', 'l'] -> []
           (canAssertO T0 A1 S7553)		; A1: ['a', 'i', 'h', 'k', 'm', 'l'] -> []
           (canAssertO T0 A1 S7041)		; A1: ['a', 'i', 'h', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S7937)		; A1: ['a', 'i', 'k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S7809)		; A1: ['a', 'h', 'k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S8064)		; A1: ['i', 'h', 'k', 'j', 'm', 'l'] -> []
           (canAssertO T0 A1 S8065)		; A1: ['a', 'i', 'h', 'k', 'j', 'm', 'l'] -> []
    )

    (:goal (> (prob-of-success) 0))

    (:metric maximize (prob-of-success) )
)