(define (problem cycle4)
    (:domain StrategicArgumentation)
    (:objects a h i g f - arg
              S0 S1 S128 S256 S64 S32 S129 S257 S65 S33 S384 S192 S160 S320 S288 S96 S385 S193 S161 S321 S289 S97 S448 S416 S224 S352 S449 S417 S225 S353 S480 S481 - setOfArgsP
              T0 T4 T2 T16 T8 T6 T20 T12 T18 T10 T24 T22 T14 T28 T26 T30 - setOfArgsO
              A2 - agent )

    (:init (= (stage) 0)

           (canAssertP a)
           (canAssertP h)
           (canAssertP i)
           (canAssertP g)
           (canAssertP f)

           (= (prob-belief A2) 1)

           (= (prob-of-success) 0)

           (successful S1 T0)		; (['a'], [])
           (successful S129 T0)		; (['a', 'h'], [])
           (successful S129 T8)		; (['a', 'h'], ['d'])
           (successful S257 T0)		; (['a', 'i'], [])
           (successful S257 T16)		; (['a', 'i'], ['e'])
           (successful S65 T0)		; (['a', 'g'], [])
           (successful S65 T4)		; (['a', 'g'], ['c'])
           (successful S33 T0)		; (['a', 'f'], [])
           (successful S33 T2)		; (['a', 'f'], ['b'])
           (successful S385 T0)		; (['a', 'h', 'i'], [])
           (successful S385 T8)		; (['a', 'h', 'i'], ['d'])
           (successful S193 T0)		; (['a', 'h', 'g'], [])
           (successful S193 T4)		; (['a', 'h', 'g'], ['c'])
           (successful S161 T0)		; (['a', 'h', 'f'], [])
           (successful S161 T2)		; (['a', 'h', 'f'], ['b'])
           (successful S161 T8)		; (['a', 'h', 'f'], ['d'])
           (successful S161 T10)		; (['a', 'h', 'f'], ['b', 'd'])
           (successful S321 T0)		; (['a', 'i', 'g'], [])
           (successful S321 T4)		; (['a', 'i', 'g'], ['c'])
           (successful S321 T16)		; (['a', 'i', 'g'], ['e'])
           (successful S321 T20)		; (['a', 'i', 'g'], ['c', 'e'])
           (successful S289 T0)		; (['a', 'i', 'f'], [])
           (successful S289 T16)		; (['a', 'i', 'f'], ['e'])
           (successful S97 T0)		; (['a', 'g', 'f'], [])
           (successful S97 T2)		; (['a', 'g', 'f'], ['b'])
           (successful S449 T0)		; (['a', 'h', 'i', 'g'], [])
           (successful S449 T4)		; (['a', 'h', 'i', 'g'], ['c'])
           (successful S449 T16)		; (['a', 'h', 'i', 'g'], ['e'])
           (successful S449 T20)		; (['a', 'h', 'i', 'g'], ['c', 'e'])
           (successful S417 T0)		; (['a', 'h', 'i', 'f'], [])
           (successful S417 T2)		; (['a', 'h', 'i', 'f'], ['b'])
           (successful S417 T8)		; (['a', 'h', 'i', 'f'], ['d'])
           (successful S417 T10)		; (['a', 'h', 'i', 'f'], ['b', 'd'])
           (successful S225 T0)		; (['a', 'h', 'g', 'f'], [])
           (successful S225 T2)		; (['a', 'h', 'g', 'f'], ['b'])
           (successful S225 T8)		; (['a', 'h', 'g', 'f'], ['d'])
           (successful S225 T10)		; (['a', 'h', 'g', 'f'], ['b', 'd'])
           (successful S353 T0)		; (['a', 'i', 'g', 'f'], [])
           (successful S353 T4)		; (['a', 'i', 'g', 'f'], ['c'])
           (successful S353 T16)		; (['a', 'i', 'g', 'f'], ['e'])
           (successful S353 T20)		; (['a', 'i', 'g', 'f'], ['c', 'e'])
           (successful S481 T0)		; (['a', 'h', 'i', 'g', 'f'], [])

           (dialogueP S97)
           (dialogueO A2 T6)

           (addP a S0 S1)		; a + [] = ['a']
           (addP a S1 S1)		; a + ['a'] = ['a']
           (addP a S128 S129)		; a + ['h'] = ['a', 'h']
           (addP a S256 S257)		; a + ['i'] = ['i', 'a']
           (addP a S64 S65)		; a + ['g'] = ['a', 'g']
           (addP a S32 S33)		; a + ['f'] = ['a', 'f']
           (addP a S129 S129)		; a + ['a', 'h'] = ['a', 'h']
           (addP a S257 S257)		; a + ['a', 'i'] = ['a', 'i']
           (addP a S65 S65)		; a + ['a', 'g'] = ['a', 'g']
           (addP a S33 S33)		; a + ['a', 'f'] = ['a', 'f']
           (addP a S384 S385)		; a + ['h', 'i'] = ['i', 'h', 'a']
           (addP a S192 S193)		; a + ['h', 'g'] = ['a', 'h', 'g']
           (addP a S160 S161)		; a + ['h', 'f'] = ['a', 'h', 'f']
           (addP a S320 S321)		; a + ['i', 'g'] = ['i', 'a', 'g']
           (addP a S288 S289)		; a + ['i', 'f'] = ['i', 'a', 'f']
           (addP a S96 S97)		; a + ['g', 'f'] = ['a', 'g', 'f']
           (addP a S385 S385)		; a + ['a', 'h', 'i'] = ['a', 'h', 'i']
           (addP a S193 S193)		; a + ['a', 'h', 'g'] = ['a', 'h', 'g']
           (addP a S161 S161)		; a + ['a', 'h', 'f'] = ['a', 'h', 'f']
           (addP a S321 S321)		; a + ['a', 'i', 'g'] = ['a', 'i', 'g']
           (addP a S289 S289)		; a + ['a', 'i', 'f'] = ['a', 'i', 'f']
           (addP a S97 S97)		; a + ['a', 'g', 'f'] = ['a', 'g', 'f']
           (addP a S448 S449)		; a + ['h', 'i', 'g'] = ['i', 'h', 'a', 'g']
           (addP a S416 S417)		; a + ['h', 'i', 'f'] = ['i', 'h', 'a', 'f']
           (addP a S224 S225)		; a + ['h', 'g', 'f'] = ['a', 'h', 'g', 'f']
           (addP a S352 S353)		; a + ['i', 'g', 'f'] = ['i', 'a', 'g', 'f']
           (addP a S449 S449)		; a + ['a', 'h', 'i', 'g'] = ['a', 'h', 'i', 'g']
           (addP a S417 S417)		; a + ['a', 'h', 'i', 'f'] = ['a', 'h', 'i', 'f']
           (addP a S225 S225)		; a + ['a', 'h', 'g', 'f'] = ['a', 'h', 'g', 'f']
           (addP a S353 S353)		; a + ['a', 'i', 'g', 'f'] = ['a', 'i', 'g', 'f']
           (addP a S480 S481)		; a + ['h', 'i', 'g', 'f'] = ['i', 'h', 'a', 'g', 'f']
           (addP a S481 S481)		; a + ['a', 'h', 'i', 'g', 'f'] = ['a', 'g', 'f', 'i', 'h']
           (addP h S0 S128)		; h + [] = ['h']
           (addP h S1 S129)		; h + ['a'] = ['a', 'h']
           (addP h S128 S128)		; h + ['h'] = ['h']
           (addP h S256 S384)		; h + ['i'] = ['i', 'h']
           (addP h S64 S192)		; h + ['g'] = ['h', 'g']
           (addP h S32 S160)		; h + ['f'] = ['h', 'f']
           (addP h S129 S129)		; h + ['a', 'h'] = ['a', 'h']
           (addP h S257 S385)		; h + ['a', 'i'] = ['a', 'i', 'h']
           (addP h S65 S193)		; h + ['a', 'g'] = ['a', 'h', 'g']
           (addP h S33 S161)		; h + ['a', 'f'] = ['a', 'h', 'f']
           (addP h S384 S384)		; h + ['h', 'i'] = ['i', 'h']
           (addP h S192 S192)		; h + ['h', 'g'] = ['h', 'g']
           (addP h S160 S160)		; h + ['h', 'f'] = ['h', 'f']
           (addP h S320 S448)		; h + ['i', 'g'] = ['i', 'h', 'g']
           (addP h S288 S416)		; h + ['i', 'f'] = ['i', 'h', 'f']
           (addP h S96 S224)		; h + ['g', 'f'] = ['h', 'g', 'f']
           (addP h S385 S385)		; h + ['a', 'h', 'i'] = ['a', 'h', 'i']
           (addP h S193 S193)		; h + ['a', 'h', 'g'] = ['a', 'h', 'g']
           (addP h S161 S161)		; h + ['a', 'h', 'f'] = ['a', 'h', 'f']
           (addP h S321 S449)		; h + ['a', 'i', 'g'] = ['a', 'i', 'g', 'h']
           (addP h S289 S417)		; h + ['a', 'i', 'f'] = ['a', 'i', 'h', 'f']
           (addP h S97 S225)		; h + ['a', 'g', 'f'] = ['a', 'h', 'g', 'f']
           (addP h S448 S448)		; h + ['h', 'i', 'g'] = ['i', 'h', 'g']
           (addP h S416 S416)		; h + ['h', 'i', 'f'] = ['i', 'h', 'f']
           (addP h S224 S224)		; h + ['h', 'g', 'f'] = ['h', 'g', 'f']
           (addP h S352 S480)		; h + ['i', 'g', 'f'] = ['i', 'h', 'g', 'f']
           (addP h S449 S449)		; h + ['a', 'h', 'i', 'g'] = ['a', 'h', 'i', 'g']
           (addP h S417 S417)		; h + ['a', 'h', 'i', 'f'] = ['a', 'h', 'i', 'f']
           (addP h S225 S225)		; h + ['a', 'h', 'g', 'f'] = ['a', 'h', 'g', 'f']
           (addP h S353 S481)		; h + ['a', 'i', 'g', 'f'] = ['a', 'i', 'h', 'g', 'f']
           (addP h S480 S480)		; h + ['h', 'i', 'g', 'f'] = ['i', 'h', 'g', 'f']
           (addP h S481 S481)		; h + ['a', 'h', 'i', 'g', 'f'] = ['a', 'g', 'f', 'i', 'h']
           (addP i S0 S256)		; i + [] = ['i']
           (addP i S1 S257)		; i + ['a'] = ['a', 'i']
           (addP i S128 S384)		; i + ['h'] = ['i', 'h']
           (addP i S256 S256)		; i + ['i'] = ['i']
           (addP i S64 S320)		; i + ['g'] = ['i', 'g']
           (addP i S32 S288)		; i + ['f'] = ['i', 'f']
           (addP i S129 S385)		; i + ['a', 'h'] = ['a', 'h', 'i']
           (addP i S257 S257)		; i + ['a', 'i'] = ['a', 'i']
           (addP i S65 S321)		; i + ['a', 'g'] = ['a', 'i', 'g']
           (addP i S33 S289)		; i + ['a', 'f'] = ['a', 'i', 'f']
           (addP i S384 S384)		; i + ['h', 'i'] = ['i', 'h']
           (addP i S192 S448)		; i + ['h', 'g'] = ['i', 'h', 'g']
           (addP i S160 S416)		; i + ['h', 'f'] = ['i', 'h', 'f']
           (addP i S320 S320)		; i + ['i', 'g'] = ['i', 'g']
           (addP i S288 S288)		; i + ['i', 'f'] = ['i', 'f']
           (addP i S96 S352)		; i + ['g', 'f'] = ['i', 'g', 'f']
           (addP i S385 S385)		; i + ['a', 'h', 'i'] = ['a', 'h', 'i']
           (addP i S193 S449)		; i + ['a', 'h', 'g'] = ['a', 'h', 'i', 'g']
           (addP i S161 S417)		; i + ['a', 'h', 'f'] = ['a', 'h', 'i', 'f']
           (addP i S321 S321)		; i + ['a', 'i', 'g'] = ['a', 'i', 'g']
           (addP i S289 S289)		; i + ['a', 'i', 'f'] = ['a', 'i', 'f']
           (addP i S97 S353)		; i + ['a', 'g', 'f'] = ['a', 'i', 'g', 'f']
           (addP i S448 S448)		; i + ['h', 'i', 'g'] = ['i', 'h', 'g']
           (addP i S416 S416)		; i + ['h', 'i', 'f'] = ['i', 'h', 'f']
           (addP i S224 S480)		; i + ['h', 'g', 'f'] = ['i', 'h', 'g', 'f']
           (addP i S352 S352)		; i + ['i', 'g', 'f'] = ['i', 'g', 'f']
           (addP i S449 S449)		; i + ['a', 'h', 'i', 'g'] = ['a', 'h', 'i', 'g']
           (addP i S417 S417)		; i + ['a', 'h', 'i', 'f'] = ['a', 'h', 'i', 'f']
           (addP i S225 S481)		; i + ['a', 'h', 'g', 'f'] = ['a', 'h', 'i', 'g', 'f']
           (addP i S353 S353)		; i + ['a', 'i', 'g', 'f'] = ['a', 'i', 'g', 'f']
           (addP i S480 S480)		; i + ['h', 'i', 'g', 'f'] = ['i', 'h', 'g', 'f']
           (addP i S481 S481)		; i + ['a', 'h', 'i', 'g', 'f'] = ['a', 'g', 'f', 'i', 'h']
           (addP g S0 S64)		; g + [] = ['g']
           (addP g S1 S65)		; g + ['a'] = ['a', 'g']
           (addP g S128 S192)		; g + ['h'] = ['h', 'g']
           (addP g S256 S320)		; g + ['i'] = ['i', 'g']
           (addP g S64 S64)		; g + ['g'] = ['g']
           (addP g S32 S96)		; g + ['f'] = ['g', 'f']
           (addP g S129 S193)		; g + ['a', 'h'] = ['a', 'h', 'g']
           (addP g S257 S321)		; g + ['a', 'i'] = ['a', 'i', 'g']
           (addP g S65 S65)		; g + ['a', 'g'] = ['a', 'g']
           (addP g S33 S97)		; g + ['a', 'f'] = ['a', 'g', 'f']
           (addP g S384 S448)		; g + ['h', 'i'] = ['i', 'h', 'g']
           (addP g S192 S192)		; g + ['h', 'g'] = ['h', 'g']
           (addP g S160 S224)		; g + ['h', 'f'] = ['h', 'g', 'f']
           (addP g S320 S320)		; g + ['i', 'g'] = ['i', 'g']
           (addP g S288 S352)		; g + ['i', 'f'] = ['i', 'g', 'f']
           (addP g S96 S96)		; g + ['g', 'f'] = ['g', 'f']
           (addP g S385 S449)		; g + ['a', 'h', 'i'] = ['a', 'h', 'i', 'g']
           (addP g S193 S193)		; g + ['a', 'h', 'g'] = ['a', 'h', 'g']
           (addP g S161 S225)		; g + ['a', 'h', 'f'] = ['a', 'h', 'g', 'f']
           (addP g S321 S321)		; g + ['a', 'i', 'g'] = ['a', 'i', 'g']
           (addP g S289 S353)		; g + ['a', 'i', 'f'] = ['a', 'i', 'g', 'f']
           (addP g S97 S97)		; g + ['a', 'g', 'f'] = ['a', 'g', 'f']
           (addP g S448 S448)		; g + ['h', 'i', 'g'] = ['i', 'h', 'g']
           (addP g S416 S480)		; g + ['h', 'i', 'f'] = ['i', 'h', 'g', 'f']
           (addP g S224 S224)		; g + ['h', 'g', 'f'] = ['h', 'g', 'f']
           (addP g S352 S352)		; g + ['i', 'g', 'f'] = ['i', 'g', 'f']
           (addP g S449 S449)		; g + ['a', 'h', 'i', 'g'] = ['a', 'h', 'i', 'g']
           (addP g S417 S481)		; g + ['a', 'h', 'i', 'f'] = ['a', 'h', 'i', 'g', 'f']
           (addP g S225 S225)		; g + ['a', 'h', 'g', 'f'] = ['a', 'h', 'g', 'f']
           (addP g S353 S353)		; g + ['a', 'i', 'g', 'f'] = ['a', 'i', 'g', 'f']
           (addP g S480 S480)		; g + ['h', 'i', 'g', 'f'] = ['i', 'h', 'g', 'f']
           (addP g S481 S481)		; g + ['a', 'h', 'i', 'g', 'f'] = ['a', 'g', 'f', 'i', 'h']
           (addP f S0 S32)		; f + [] = ['f']
           (addP f S1 S33)		; f + ['a'] = ['a', 'f']
           (addP f S128 S160)		; f + ['h'] = ['h', 'f']
           (addP f S256 S288)		; f + ['i'] = ['i', 'f']
           (addP f S64 S96)		; f + ['g'] = ['g', 'f']
           (addP f S32 S32)		; f + ['f'] = ['f']
           (addP f S129 S161)		; f + ['a', 'h'] = ['a', 'h', 'f']
           (addP f S257 S289)		; f + ['a', 'i'] = ['a', 'i', 'f']
           (addP f S65 S97)		; f + ['a', 'g'] = ['a', 'g', 'f']
           (addP f S33 S33)		; f + ['a', 'f'] = ['a', 'f']
           (addP f S384 S416)		; f + ['h', 'i'] = ['i', 'h', 'f']
           (addP f S192 S224)		; f + ['h', 'g'] = ['h', 'g', 'f']
           (addP f S160 S160)		; f + ['h', 'f'] = ['h', 'f']
           (addP f S320 S352)		; f + ['i', 'g'] = ['i', 'g', 'f']
           (addP f S288 S288)		; f + ['i', 'f'] = ['i', 'f']
           (addP f S96 S96)		; f + ['g', 'f'] = ['g', 'f']
           (addP f S385 S417)		; f + ['a', 'h', 'i'] = ['a', 'h', 'i', 'f']
           (addP f S193 S225)		; f + ['a', 'h', 'g'] = ['a', 'h', 'g', 'f']
           (addP f S161 S161)		; f + ['a', 'h', 'f'] = ['a', 'h', 'f']
           (addP f S321 S353)		; f + ['a', 'i', 'g'] = ['a', 'i', 'g', 'f']
           (addP f S289 S289)		; f + ['a', 'i', 'f'] = ['a', 'i', 'f']
           (addP f S97 S97)		; f + ['a', 'g', 'f'] = ['a', 'g', 'f']
           (addP f S448 S480)		; f + ['h', 'i', 'g'] = ['i', 'h', 'g', 'f']
           (addP f S416 S416)		; f + ['h', 'i', 'f'] = ['i', 'h', 'f']
           (addP f S224 S224)		; f + ['h', 'g', 'f'] = ['h', 'g', 'f']
           (addP f S352 S352)		; f + ['i', 'g', 'f'] = ['i', 'g', 'f']
           (addP f S449 S481)		; f + ['a', 'h', 'i', 'g'] = ['a', 'h', 'i', 'g', 'f']
           (addP f S417 S417)		; f + ['a', 'h', 'i', 'f'] = ['a', 'h', 'i', 'f']
           (addP f S225 S225)		; f + ['a', 'h', 'g', 'f'] = ['a', 'h', 'g', 'f']
           (addP f S353 S353)		; f + ['a', 'i', 'g', 'f'] = ['a', 'i', 'g', 'f']
           (addP f S480 S480)		; f + ['h', 'i', 'g', 'f'] = ['i', 'h', 'g', 'f']
           (addP f S481 S481)		; f + ['a', 'h', 'i', 'g', 'f'] = ['a', 'g', 'f', 'i', 'h']

           (addO T0 T0 T0)		; [] + [] = []
           (addO T0 T4 T4)		; [] + ['c'] = ['c']
           (addO T0 T2 T2)		; [] + ['b'] = ['b']
           (addO T0 T16 T16)		; [] + ['e'] = ['e']
           (addO T0 T8 T8)		; [] + ['d'] = ['d']
           (addO T0 T6 T6)		; [] + ['c', 'b'] = ['c', 'b']
           (addO T0 T20 T20)		; [] + ['c', 'e'] = ['c', 'e']
           (addO T0 T12 T12)		; [] + ['c', 'd'] = ['c', 'd']
           (addO T0 T18 T18)		; [] + ['b', 'e'] = ['b', 'e']
           (addO T0 T10 T10)		; [] + ['b', 'd'] = ['b', 'd']
           (addO T0 T24 T24)		; [] + ['e', 'd'] = ['e', 'd']
           (addO T0 T22 T22)		; [] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T0 T14 T14)		; [] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T0 T28 T28)		; [] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T0 T26 T26)		; [] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T0 T30 T30)		; [] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T4 T0 T4)		; ['c'] + [] = ['c']
           (addO T4 T4 T4)		; ['c'] + ['c'] = ['c']
           (addO T4 T2 T6)		; ['c'] + ['b'] = ['c', 'b']
           (addO T4 T16 T20)		; ['c'] + ['e'] = ['c', 'e']
           (addO T4 T8 T12)		; ['c'] + ['d'] = ['c', 'd']
           (addO T4 T6 T6)		; ['c'] + ['c', 'b'] = ['c', 'b']
           (addO T4 T20 T20)		; ['c'] + ['c', 'e'] = ['c', 'e']
           (addO T4 T12 T12)		; ['c'] + ['c', 'd'] = ['c', 'd']
           (addO T4 T18 T22)		; ['c'] + ['b', 'e'] = ['c', 'b', 'e']
           (addO T4 T10 T14)		; ['c'] + ['b', 'd'] = ['c', 'b', 'd']
           (addO T4 T24 T28)		; ['c'] + ['e', 'd'] = ['c', 'e', 'd']
           (addO T4 T22 T22)		; ['c'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T4 T14 T14)		; ['c'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T4 T28 T28)		; ['c'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T4 T26 T30)		; ['c'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T4 T30 T30)		; ['c'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T2 T0 T2)		; ['b'] + [] = ['b']
           (addO T2 T4 T6)		; ['b'] + ['c'] = ['c', 'b']
           (addO T2 T2 T2)		; ['b'] + ['b'] = ['b']
           (addO T2 T16 T18)		; ['b'] + ['e'] = ['b', 'e']
           (addO T2 T8 T10)		; ['b'] + ['d'] = ['b', 'd']
           (addO T2 T6 T6)		; ['b'] + ['c', 'b'] = ['c', 'b']
           (addO T2 T20 T22)		; ['b'] + ['c', 'e'] = ['c', 'b', 'e']
           (addO T2 T12 T14)		; ['b'] + ['c', 'd'] = ['c', 'b', 'd']
           (addO T2 T18 T18)		; ['b'] + ['b', 'e'] = ['b', 'e']
           (addO T2 T10 T10)		; ['b'] + ['b', 'd'] = ['b', 'd']
           (addO T2 T24 T26)		; ['b'] + ['e', 'd'] = ['b', 'e', 'd']
           (addO T2 T22 T22)		; ['b'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T2 T14 T14)		; ['b'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T2 T28 T30)		; ['b'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T2 T26 T26)		; ['b'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T2 T30 T30)		; ['b'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T16 T0 T16)		; ['e'] + [] = ['e']
           (addO T16 T4 T20)		; ['e'] + ['c'] = ['c', 'e']
           (addO T16 T2 T18)		; ['e'] + ['b'] = ['b', 'e']
           (addO T16 T16 T16)		; ['e'] + ['e'] = ['e']
           (addO T16 T8 T24)		; ['e'] + ['d'] = ['e', 'd']
           (addO T16 T6 T22)		; ['e'] + ['c', 'b'] = ['c', 'b', 'e']
           (addO T16 T20 T20)		; ['e'] + ['c', 'e'] = ['c', 'e']
           (addO T16 T12 T28)		; ['e'] + ['c', 'd'] = ['c', 'e', 'd']
           (addO T16 T18 T18)		; ['e'] + ['b', 'e'] = ['b', 'e']
           (addO T16 T10 T26)		; ['e'] + ['b', 'd'] = ['b', 'e', 'd']
           (addO T16 T24 T24)		; ['e'] + ['e', 'd'] = ['e', 'd']
           (addO T16 T22 T22)		; ['e'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T16 T14 T30)		; ['e'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T16 T28 T28)		; ['e'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T16 T26 T26)		; ['e'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T16 T30 T30)		; ['e'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T8 T0 T8)		; ['d'] + [] = ['d']
           (addO T8 T4 T12)		; ['d'] + ['c'] = ['c', 'd']
           (addO T8 T2 T10)		; ['d'] + ['b'] = ['b', 'd']
           (addO T8 T16 T24)		; ['d'] + ['e'] = ['e', 'd']
           (addO T8 T8 T8)		; ['d'] + ['d'] = ['d']
           (addO T8 T6 T14)		; ['d'] + ['c', 'b'] = ['c', 'b', 'd']
           (addO T8 T20 T28)		; ['d'] + ['c', 'e'] = ['c', 'e', 'd']
           (addO T8 T12 T12)		; ['d'] + ['c', 'd'] = ['c', 'd']
           (addO T8 T18 T26)		; ['d'] + ['b', 'e'] = ['b', 'e', 'd']
           (addO T8 T10 T10)		; ['d'] + ['b', 'd'] = ['b', 'd']
           (addO T8 T24 T24)		; ['d'] + ['e', 'd'] = ['e', 'd']
           (addO T8 T22 T30)		; ['d'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T8 T14 T14)		; ['d'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T8 T28 T28)		; ['d'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T8 T26 T26)		; ['d'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T8 T30 T30)		; ['d'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T6 T0 T6)		; ['c', 'b'] + [] = ['c', 'b']
           (addO T6 T4 T6)		; ['c', 'b'] + ['c'] = ['c', 'b']
           (addO T6 T2 T6)		; ['c', 'b'] + ['b'] = ['c', 'b']
           (addO T6 T16 T22)		; ['c', 'b'] + ['e'] = ['c', 'b', 'e']
           (addO T6 T8 T14)		; ['c', 'b'] + ['d'] = ['c', 'b', 'd']
           (addO T6 T6 T6)		; ['c', 'b'] + ['c', 'b'] = ['c', 'b']
           (addO T6 T20 T22)		; ['c', 'b'] + ['c', 'e'] = ['c', 'b', 'e']
           (addO T6 T12 T14)		; ['c', 'b'] + ['c', 'd'] = ['c', 'b', 'd']
           (addO T6 T18 T22)		; ['c', 'b'] + ['b', 'e'] = ['c', 'b', 'e']
           (addO T6 T10 T14)		; ['c', 'b'] + ['b', 'd'] = ['c', 'b', 'd']
           (addO T6 T24 T30)		; ['c', 'b'] + ['e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T6 T22 T22)		; ['c', 'b'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T6 T14 T14)		; ['c', 'b'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T6 T28 T30)		; ['c', 'b'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T6 T26 T30)		; ['c', 'b'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T6 T30 T30)		; ['c', 'b'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T20 T0 T20)		; ['c', 'e'] + [] = ['c', 'e']
           (addO T20 T4 T20)		; ['c', 'e'] + ['c'] = ['c', 'e']
           (addO T20 T2 T22)		; ['c', 'e'] + ['b'] = ['c', 'b', 'e']
           (addO T20 T16 T20)		; ['c', 'e'] + ['e'] = ['c', 'e']
           (addO T20 T8 T28)		; ['c', 'e'] + ['d'] = ['c', 'e', 'd']
           (addO T20 T6 T22)		; ['c', 'e'] + ['c', 'b'] = ['c', 'b', 'e']
           (addO T20 T20 T20)		; ['c', 'e'] + ['c', 'e'] = ['c', 'e']
           (addO T20 T12 T28)		; ['c', 'e'] + ['c', 'd'] = ['c', 'e', 'd']
           (addO T20 T18 T22)		; ['c', 'e'] + ['b', 'e'] = ['c', 'b', 'e']
           (addO T20 T10 T30)		; ['c', 'e'] + ['b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T20 T24 T28)		; ['c', 'e'] + ['e', 'd'] = ['c', 'e', 'd']
           (addO T20 T22 T22)		; ['c', 'e'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T20 T14 T30)		; ['c', 'e'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T20 T28 T28)		; ['c', 'e'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T20 T26 T30)		; ['c', 'e'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T20 T30 T30)		; ['c', 'e'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T12 T0 T12)		; ['c', 'd'] + [] = ['c', 'd']
           (addO T12 T4 T12)		; ['c', 'd'] + ['c'] = ['c', 'd']
           (addO T12 T2 T14)		; ['c', 'd'] + ['b'] = ['c', 'b', 'd']
           (addO T12 T16 T28)		; ['c', 'd'] + ['e'] = ['c', 'e', 'd']
           (addO T12 T8 T12)		; ['c', 'd'] + ['d'] = ['c', 'd']
           (addO T12 T6 T14)		; ['c', 'd'] + ['c', 'b'] = ['c', 'b', 'd']
           (addO T12 T20 T28)		; ['c', 'd'] + ['c', 'e'] = ['c', 'e', 'd']
           (addO T12 T12 T12)		; ['c', 'd'] + ['c', 'd'] = ['c', 'd']
           (addO T12 T18 T30)		; ['c', 'd'] + ['b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T12 T10 T14)		; ['c', 'd'] + ['b', 'd'] = ['c', 'b', 'd']
           (addO T12 T24 T28)		; ['c', 'd'] + ['e', 'd'] = ['c', 'e', 'd']
           (addO T12 T22 T30)		; ['c', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T12 T14 T14)		; ['c', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T12 T28 T28)		; ['c', 'd'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T12 T26 T30)		; ['c', 'd'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T12 T30 T30)		; ['c', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T18 T0 T18)		; ['b', 'e'] + [] = ['b', 'e']
           (addO T18 T4 T22)		; ['b', 'e'] + ['c'] = ['c', 'b', 'e']
           (addO T18 T2 T18)		; ['b', 'e'] + ['b'] = ['b', 'e']
           (addO T18 T16 T18)		; ['b', 'e'] + ['e'] = ['b', 'e']
           (addO T18 T8 T26)		; ['b', 'e'] + ['d'] = ['b', 'e', 'd']
           (addO T18 T6 T22)		; ['b', 'e'] + ['c', 'b'] = ['c', 'b', 'e']
           (addO T18 T20 T22)		; ['b', 'e'] + ['c', 'e'] = ['c', 'b', 'e']
           (addO T18 T12 T30)		; ['b', 'e'] + ['c', 'd'] = ['c', 'b', 'e', 'd']
           (addO T18 T18 T18)		; ['b', 'e'] + ['b', 'e'] = ['b', 'e']
           (addO T18 T10 T26)		; ['b', 'e'] + ['b', 'd'] = ['b', 'e', 'd']
           (addO T18 T24 T26)		; ['b', 'e'] + ['e', 'd'] = ['b', 'e', 'd']
           (addO T18 T22 T22)		; ['b', 'e'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T18 T14 T30)		; ['b', 'e'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T18 T28 T30)		; ['b', 'e'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T18 T26 T26)		; ['b', 'e'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T18 T30 T30)		; ['b', 'e'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T10 T0 T10)		; ['b', 'd'] + [] = ['b', 'd']
           (addO T10 T4 T14)		; ['b', 'd'] + ['c'] = ['c', 'b', 'd']
           (addO T10 T2 T10)		; ['b', 'd'] + ['b'] = ['b', 'd']
           (addO T10 T16 T26)		; ['b', 'd'] + ['e'] = ['b', 'e', 'd']
           (addO T10 T8 T10)		; ['b', 'd'] + ['d'] = ['b', 'd']
           (addO T10 T6 T14)		; ['b', 'd'] + ['c', 'b'] = ['c', 'b', 'd']
           (addO T10 T20 T30)		; ['b', 'd'] + ['c', 'e'] = ['c', 'b', 'e', 'd']
           (addO T10 T12 T14)		; ['b', 'd'] + ['c', 'd'] = ['c', 'b', 'd']
           (addO T10 T18 T26)		; ['b', 'd'] + ['b', 'e'] = ['b', 'e', 'd']
           (addO T10 T10 T10)		; ['b', 'd'] + ['b', 'd'] = ['b', 'd']
           (addO T10 T24 T26)		; ['b', 'd'] + ['e', 'd'] = ['b', 'e', 'd']
           (addO T10 T22 T30)		; ['b', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T10 T14 T14)		; ['b', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T10 T28 T30)		; ['b', 'd'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T10 T26 T26)		; ['b', 'd'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T10 T30 T30)		; ['b', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T24 T0 T24)		; ['e', 'd'] + [] = ['e', 'd']
           (addO T24 T4 T28)		; ['e', 'd'] + ['c'] = ['c', 'e', 'd']
           (addO T24 T2 T26)		; ['e', 'd'] + ['b'] = ['b', 'e', 'd']
           (addO T24 T16 T24)		; ['e', 'd'] + ['e'] = ['e', 'd']
           (addO T24 T8 T24)		; ['e', 'd'] + ['d'] = ['e', 'd']
           (addO T24 T6 T30)		; ['e', 'd'] + ['c', 'b'] = ['c', 'b', 'e', 'd']
           (addO T24 T20 T28)		; ['e', 'd'] + ['c', 'e'] = ['c', 'e', 'd']
           (addO T24 T12 T28)		; ['e', 'd'] + ['c', 'd'] = ['c', 'e', 'd']
           (addO T24 T18 T26)		; ['e', 'd'] + ['b', 'e'] = ['b', 'e', 'd']
           (addO T24 T10 T26)		; ['e', 'd'] + ['b', 'd'] = ['b', 'e', 'd']
           (addO T24 T24 T24)		; ['e', 'd'] + ['e', 'd'] = ['e', 'd']
           (addO T24 T22 T30)		; ['e', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T24 T14 T30)		; ['e', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T24 T28 T28)		; ['e', 'd'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T24 T26 T26)		; ['e', 'd'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T24 T30 T30)		; ['e', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T0 T22)		; ['c', 'b', 'e'] + [] = ['c', 'b', 'e']
           (addO T22 T4 T22)		; ['c', 'b', 'e'] + ['c'] = ['c', 'b', 'e']
           (addO T22 T2 T22)		; ['c', 'b', 'e'] + ['b'] = ['c', 'b', 'e']
           (addO T22 T16 T22)		; ['c', 'b', 'e'] + ['e'] = ['c', 'b', 'e']
           (addO T22 T8 T30)		; ['c', 'b', 'e'] + ['d'] = ['c', 'b', 'e', 'd']
           (addO T22 T6 T22)		; ['c', 'b', 'e'] + ['c', 'b'] = ['c', 'b', 'e']
           (addO T22 T20 T22)		; ['c', 'b', 'e'] + ['c', 'e'] = ['c', 'b', 'e']
           (addO T22 T12 T30)		; ['c', 'b', 'e'] + ['c', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T18 T22)		; ['c', 'b', 'e'] + ['b', 'e'] = ['c', 'b', 'e']
           (addO T22 T10 T30)		; ['c', 'b', 'e'] + ['b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T24 T30)		; ['c', 'b', 'e'] + ['e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T22 T22)		; ['c', 'b', 'e'] + ['c', 'b', 'e'] = ['c', 'b', 'e']
           (addO T22 T14 T30)		; ['c', 'b', 'e'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T28 T30)		; ['c', 'b', 'e'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T26 T30)		; ['c', 'b', 'e'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T22 T30 T30)		; ['c', 'b', 'e'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T14 T0 T14)		; ['c', 'b', 'd'] + [] = ['c', 'b', 'd']
           (addO T14 T4 T14)		; ['c', 'b', 'd'] + ['c'] = ['c', 'b', 'd']
           (addO T14 T2 T14)		; ['c', 'b', 'd'] + ['b'] = ['c', 'b', 'd']
           (addO T14 T16 T30)		; ['c', 'b', 'd'] + ['e'] = ['c', 'b', 'e', 'd']
           (addO T14 T8 T14)		; ['c', 'b', 'd'] + ['d'] = ['c', 'b', 'd']
           (addO T14 T6 T14)		; ['c', 'b', 'd'] + ['c', 'b'] = ['c', 'b', 'd']
           (addO T14 T20 T30)		; ['c', 'b', 'd'] + ['c', 'e'] = ['c', 'b', 'e', 'd']
           (addO T14 T12 T14)		; ['c', 'b', 'd'] + ['c', 'd'] = ['c', 'b', 'd']
           (addO T14 T18 T30)		; ['c', 'b', 'd'] + ['b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T14 T10 T14)		; ['c', 'b', 'd'] + ['b', 'd'] = ['c', 'b', 'd']
           (addO T14 T24 T30)		; ['c', 'b', 'd'] + ['e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T14 T22 T30)		; ['c', 'b', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T14 T14 T14)		; ['c', 'b', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'd']
           (addO T14 T28 T30)		; ['c', 'b', 'd'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T14 T26 T30)		; ['c', 'b', 'd'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T14 T30 T30)		; ['c', 'b', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T28 T0 T28)		; ['c', 'e', 'd'] + [] = ['c', 'e', 'd']
           (addO T28 T4 T28)		; ['c', 'e', 'd'] + ['c'] = ['c', 'e', 'd']
           (addO T28 T2 T30)		; ['c', 'e', 'd'] + ['b'] = ['c', 'b', 'e', 'd']
           (addO T28 T16 T28)		; ['c', 'e', 'd'] + ['e'] = ['c', 'e', 'd']
           (addO T28 T8 T28)		; ['c', 'e', 'd'] + ['d'] = ['c', 'e', 'd']
           (addO T28 T6 T30)		; ['c', 'e', 'd'] + ['c', 'b'] = ['c', 'b', 'e', 'd']
           (addO T28 T20 T28)		; ['c', 'e', 'd'] + ['c', 'e'] = ['c', 'e', 'd']
           (addO T28 T12 T28)		; ['c', 'e', 'd'] + ['c', 'd'] = ['c', 'e', 'd']
           (addO T28 T18 T30)		; ['c', 'e', 'd'] + ['b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T28 T10 T30)		; ['c', 'e', 'd'] + ['b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T28 T24 T28)		; ['c', 'e', 'd'] + ['e', 'd'] = ['c', 'e', 'd']
           (addO T28 T22 T30)		; ['c', 'e', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T28 T14 T30)		; ['c', 'e', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T28 T28 T28)		; ['c', 'e', 'd'] + ['c', 'e', 'd'] = ['c', 'e', 'd']
           (addO T28 T26 T30)		; ['c', 'e', 'd'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T28 T30 T30)		; ['c', 'e', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T26 T0 T26)		; ['b', 'e', 'd'] + [] = ['b', 'e', 'd']
           (addO T26 T4 T30)		; ['b', 'e', 'd'] + ['c'] = ['c', 'b', 'e', 'd']
           (addO T26 T2 T26)		; ['b', 'e', 'd'] + ['b'] = ['b', 'e', 'd']
           (addO T26 T16 T26)		; ['b', 'e', 'd'] + ['e'] = ['b', 'e', 'd']
           (addO T26 T8 T26)		; ['b', 'e', 'd'] + ['d'] = ['b', 'e', 'd']
           (addO T26 T6 T30)		; ['b', 'e', 'd'] + ['c', 'b'] = ['c', 'b', 'e', 'd']
           (addO T26 T20 T30)		; ['b', 'e', 'd'] + ['c', 'e'] = ['c', 'b', 'e', 'd']
           (addO T26 T12 T30)		; ['b', 'e', 'd'] + ['c', 'd'] = ['c', 'b', 'e', 'd']
           (addO T26 T18 T26)		; ['b', 'e', 'd'] + ['b', 'e'] = ['b', 'e', 'd']
           (addO T26 T10 T26)		; ['b', 'e', 'd'] + ['b', 'd'] = ['b', 'e', 'd']
           (addO T26 T24 T26)		; ['b', 'e', 'd'] + ['e', 'd'] = ['b', 'e', 'd']
           (addO T26 T22 T30)		; ['b', 'e', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T26 T14 T30)		; ['b', 'e', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T26 T28 T30)		; ['b', 'e', 'd'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T26 T26 T26)		; ['b', 'e', 'd'] + ['b', 'e', 'd'] = ['b', 'e', 'd']
           (addO T26 T30 T30)		; ['b', 'e', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T0 T30)		; ['c', 'b', 'e', 'd'] + [] = ['c', 'b', 'e', 'd']
           (addO T30 T4 T30)		; ['c', 'b', 'e', 'd'] + ['c'] = ['c', 'b', 'e', 'd']
           (addO T30 T2 T30)		; ['c', 'b', 'e', 'd'] + ['b'] = ['c', 'b', 'e', 'd']
           (addO T30 T16 T30)		; ['c', 'b', 'e', 'd'] + ['e'] = ['c', 'b', 'e', 'd']
           (addO T30 T8 T30)		; ['c', 'b', 'e', 'd'] + ['d'] = ['c', 'b', 'e', 'd']
           (addO T30 T6 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'b'] = ['c', 'b', 'e', 'd']
           (addO T30 T20 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'e'] = ['c', 'b', 'e', 'd']
           (addO T30 T12 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T18 T30)		; ['c', 'b', 'e', 'd'] + ['b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T30 T10 T30)		; ['c', 'b', 'e', 'd'] + ['b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T24 T30)		; ['c', 'b', 'e', 'd'] + ['e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T22 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'b', 'e'] = ['c', 'b', 'e', 'd']
           (addO T30 T14 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'b', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T28 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T26 T30)		; ['c', 'b', 'e', 'd'] + ['b', 'e', 'd'] = ['c', 'b', 'e', 'd']
           (addO T30 T30 T30)		; ['c', 'b', 'e', 'd'] + ['c', 'b', 'e', 'd'] = ['c', 'b', 'e', 'd']

           (canAssertO T0 A2 S0)		; A2: [] -> []
           (canAssertO T16 A2 S0)		; A2: [] -> ['e']
           (canAssertO T8 A2 S0)		; A2: [] -> ['d']
           (canAssertO T0 A2 S1)		; A2: ['a'] -> []
           (canAssertO T16 A2 S1)		; A2: ['a'] -> ['e']
           (canAssertO T8 A2 S1)		; A2: ['a'] -> ['d']
           (canAssertO T0 A2 S128)		; A2: ['h'] -> []
           (canAssertO T16 A2 S128)		; A2: ['h'] -> ['e']
           (canAssertO T8 A2 S128)		; A2: ['h'] -> ['d']
           (canAssertO T0 A2 S256)		; A2: ['i'] -> []
           (canAssertO T16 A2 S256)		; A2: ['i'] -> ['e']
           (canAssertO T8 A2 S256)		; A2: ['i'] -> ['d']
           (canAssertO T0 A2 S64)		; A2: ['g'] -> []
           (canAssertO T16 A2 S64)		; A2: ['g'] -> ['e']
           (canAssertO T8 A2 S64)		; A2: ['g'] -> ['d']
           (canAssertO T0 A2 S32)		; A2: ['f'] -> []
           (canAssertO T16 A2 S32)		; A2: ['f'] -> ['e']
           (canAssertO T8 A2 S32)		; A2: ['f'] -> ['d']
           (canAssertO T0 A2 S129)		; A2: ['a', 'h'] -> []
           (canAssertO T16 A2 S129)		; A2: ['a', 'h'] -> ['e']
           (canAssertO T8 A2 S129)		; A2: ['a', 'h'] -> ['d']
           (canAssertO T0 A2 S257)		; A2: ['a', 'i'] -> []
           (canAssertO T16 A2 S257)		; A2: ['a', 'i'] -> ['e']
           (canAssertO T8 A2 S257)		; A2: ['a', 'i'] -> ['d']
           (canAssertO T0 A2 S65)		; A2: ['a', 'g'] -> []
           (canAssertO T16 A2 S65)		; A2: ['a', 'g'] -> ['e']
           (canAssertO T8 A2 S65)		; A2: ['a', 'g'] -> ['d']
           (canAssertO T0 A2 S33)		; A2: ['a', 'f'] -> []
           (canAssertO T16 A2 S33)		; A2: ['a', 'f'] -> ['e']
           (canAssertO T8 A2 S33)		; A2: ['a', 'f'] -> ['d']
           (canAssertO T0 A2 S384)		; A2: ['h', 'i'] -> []
           (canAssertO T16 A2 S384)		; A2: ['h', 'i'] -> ['e']
           (canAssertO T8 A2 S384)		; A2: ['h', 'i'] -> ['d']
           (canAssertO T0 A2 S192)		; A2: ['h', 'g'] -> []
           (canAssertO T16 A2 S192)		; A2: ['h', 'g'] -> ['e']
           (canAssertO T8 A2 S192)		; A2: ['h', 'g'] -> ['d']
           (canAssertO T0 A2 S160)		; A2: ['h', 'f'] -> []
           (canAssertO T16 A2 S160)		; A2: ['h', 'f'] -> ['e']
           (canAssertO T8 A2 S160)		; A2: ['h', 'f'] -> ['d']
           (canAssertO T0 A2 S320)		; A2: ['i', 'g'] -> []
           (canAssertO T16 A2 S320)		; A2: ['i', 'g'] -> ['e']
           (canAssertO T8 A2 S320)		; A2: ['i', 'g'] -> ['d']
           (canAssertO T0 A2 S288)		; A2: ['i', 'f'] -> []
           (canAssertO T16 A2 S288)		; A2: ['i', 'f'] -> ['e']
           (canAssertO T8 A2 S288)		; A2: ['i', 'f'] -> ['d']
           (canAssertO T0 A2 S96)		; A2: ['g', 'f'] -> []
           (canAssertO T16 A2 S96)		; A2: ['g', 'f'] -> ['e']
           (canAssertO T8 A2 S96)		; A2: ['g', 'f'] -> ['d']
           (canAssertO T0 A2 S385)		; A2: ['a', 'h', 'i'] -> []
           (canAssertO T16 A2 S385)		; A2: ['a', 'h', 'i'] -> ['e']
           (canAssertO T8 A2 S385)		; A2: ['a', 'h', 'i'] -> ['d']
           (canAssertO T0 A2 S193)		; A2: ['a', 'h', 'g'] -> []
           (canAssertO T16 A2 S193)		; A2: ['a', 'h', 'g'] -> ['e']
           (canAssertO T8 A2 S193)		; A2: ['a', 'h', 'g'] -> ['d']
           (canAssertO T0 A2 S161)		; A2: ['a', 'h', 'f'] -> []
           (canAssertO T16 A2 S161)		; A2: ['a', 'h', 'f'] -> ['e']
           (canAssertO T8 A2 S161)		; A2: ['a', 'h', 'f'] -> ['d']
           (canAssertO T0 A2 S321)		; A2: ['a', 'i', 'g'] -> []
           (canAssertO T16 A2 S321)		; A2: ['a', 'i', 'g'] -> ['e']
           (canAssertO T8 A2 S321)		; A2: ['a', 'i', 'g'] -> ['d']
           (canAssertO T0 A2 S289)		; A2: ['a', 'i', 'f'] -> []
           (canAssertO T16 A2 S289)		; A2: ['a', 'i', 'f'] -> ['e']
           (canAssertO T8 A2 S289)		; A2: ['a', 'i', 'f'] -> ['d']
           (canAssertO T0 A2 S97)		; A2: ['a', 'g', 'f'] -> []
           (canAssertO T16 A2 S97)		; A2: ['a', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S97)		; A2: ['a', 'g', 'f'] -> ['d']
           (canAssertO T0 A2 S448)		; A2: ['h', 'i', 'g'] -> []
           (canAssertO T16 A2 S448)		; A2: ['h', 'i', 'g'] -> ['e']
           (canAssertO T8 A2 S448)		; A2: ['h', 'i', 'g'] -> ['d']
           (canAssertO T0 A2 S416)		; A2: ['h', 'i', 'f'] -> []
           (canAssertO T16 A2 S416)		; A2: ['h', 'i', 'f'] -> ['e']
           (canAssertO T8 A2 S416)		; A2: ['h', 'i', 'f'] -> ['d']
           (canAssertO T0 A2 S224)		; A2: ['h', 'g', 'f'] -> []
           (canAssertO T16 A2 S224)		; A2: ['h', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S224)		; A2: ['h', 'g', 'f'] -> ['d']
           (canAssertO T0 A2 S352)		; A2: ['i', 'g', 'f'] -> []
           (canAssertO T16 A2 S352)		; A2: ['i', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S352)		; A2: ['i', 'g', 'f'] -> ['d']
           (canAssertO T0 A2 S449)		; A2: ['a', 'h', 'i', 'g'] -> []
           (canAssertO T16 A2 S449)		; A2: ['a', 'h', 'i', 'g'] -> ['e']
           (canAssertO T8 A2 S449)		; A2: ['a', 'h', 'i', 'g'] -> ['d']
           (canAssertO T0 A2 S417)		; A2: ['a', 'h', 'i', 'f'] -> []
           (canAssertO T16 A2 S417)		; A2: ['a', 'h', 'i', 'f'] -> ['e']
           (canAssertO T8 A2 S417)		; A2: ['a', 'h', 'i', 'f'] -> ['d']
           (canAssertO T0 A2 S225)		; A2: ['a', 'h', 'g', 'f'] -> []
           (canAssertO T16 A2 S225)		; A2: ['a', 'h', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S225)		; A2: ['a', 'h', 'g', 'f'] -> ['d']
           (canAssertO T0 A2 S353)		; A2: ['a', 'i', 'g', 'f'] -> []
           (canAssertO T16 A2 S353)		; A2: ['a', 'i', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S353)		; A2: ['a', 'i', 'g', 'f'] -> ['d']
           (canAssertO T0 A2 S480)		; A2: ['h', 'i', 'g', 'f'] -> []
           (canAssertO T16 A2 S480)		; A2: ['h', 'i', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S480)		; A2: ['h', 'i', 'g', 'f'] -> ['d']
           (canAssertO T0 A2 S481)		; A2: ['a', 'h', 'i', 'g', 'f'] -> []
           (canAssertO T16 A2 S481)		; A2: ['a', 'h', 'i', 'g', 'f'] -> ['e']
           (canAssertO T8 A2 S481)		; A2: ['a', 'h', 'i', 'g', 'f'] -> ['d']
    )

    (:goal (> (prob-of-success) 0))

    (:metric maximize (prob-of-success) )
)